### ISSUE TITLE
some themes showing up as [?]

### ISSUE THREAD

**Issue by joo456** [astronautlevel2/Anemone3DS#10]
when you try apply them you get an error
[heres a crash dump lol](https://github.com/astronautlevel2/Anemone3DS/files/1268091/crash_dump_00000003.dmp.zip)

**Comment by astronautlevel2** [comment]
This is likely an invalid file that isn't actually a Theme in the Themes/ folder.

What build are you using?

**Comment by joo456** [comment]
Well it isn't invalid because they show up fine in Themely (except the last two, but they work anyway)
Apparently its the latest build compiled as a cia by hyaxo on SSS

**Comment by BernardoGiordano** [comment]
which themes are they? can you provide links for them to reproduce the issue?

**Comment by LiquidFenrir** [comment]
it sees everything in the `/Themes` folder that's a. another folder or b. a zip file as a theme, and adds it to the list, which can cause that if it's not a theme.
you shouldn't store anything else there anyway

**Comment by joo456** [comment]
New release fixed somehow /shrug
