### ISSUE TITLE
themes arent shuffling?

### ISSUE THREAD

**Issue by morepornpls** [astronautlevel2/Anemone3DS#100]
hitting B on all 10 themes id like to queue then hitting select to install, the queue dissappears. i re-queue the themes, then exit the app, and it chooses the first theme i hit B on. not sure if bug or im retarded, but please help.

**Comment by Helloman892** [comment]
The way shuffle is *meant* to work is that you:
1. Press B on each theme you want to shuffle,
1. Press SELECT to shuffle install,
1. Press START to quit, then the Home button to go back to the Home Menu.

The theme should change each time you return to the Home Menu after initiating power-off - this can be either by actually turning off the console, or just hitting the Power button and then Home (similar to how you exit Anemone). Can you clarify that that is the order that you are doing things in?

**Comment by morepornpls** [comment]
Followed those steps exactly. After hitting select to install them all, the
queue disappears. If i hit B on all 10 after this, the theme i had selected
prior stays on my home screen, same as if i dont remake the queue. Not sure
if a bug, or incorrect. ((Both of these results are after hitting
start->home, then powering off and on just to make sure))

**Comment by Helloman892** [comment]
Ah, I see.
The queue is meant to disappear after hitting SELECT - we currently have no method in place of determining what your shuffle is set to.
Are you using the latest version, v1.2.2? Just to be certain.

**Comment by morepornpls** [comment]
Yes, im on 1.2.2.

**Comment by Helloman892** [comment]
Ok, finally: 
* Are you using the 3DSX or CIA version, and if using the CIA version, have you tried reinstalling?
* Have you tried shuffling with less than 10 themes?

**Comment by morepornpls** [comment]
Cia version, will try that. And yes, tried with only two themes, after five
full restarts of the console, never shuffled.

**Comment by Helloman892** [comment]
Actually, come to think of it, I remember running into a similar issue right when I first got involved - Try using the Home Menu's built-in shuffle feature first. I *think* that was what fixed it for me.

**Comment by morepornpls** [comment]
THIS FIXED IT THANK YOU SO MUCH

**Comment by Helloman892** [comment]
Aha, sure, no worries.
