### ISSUE TITLE
Splashes not working

### ISSUE THREAD

**Issue by XpertYoungen** [astronautlevel2/Anemone3DS#102]
i started using Anemone the other day and used only themes no splashes, today i decided to try one out but for some reason when i download one either manually or by qr code they don't work and only show up in the themes folder and not splashes

**Comment by coggrindder** [comment]
I have a similar issue. I just updated to latest and when i install a splash via FTP, it shows up as a colored square. Preview is just black screen and install via QR code doesnt work for splashes at all

**Comment by Helloman892** [comment]
For a start, 'install via QR code' isn't a thing. You still have to apply the splash yourselves.

Secondly, are you sure you're using the QR scanner while in splash mode?

**Comment by coggrindder** [comment]
Yes, absolutely. I'm not that dense. And if its not a thing, why have the
"open qr scanner" around?

**Comment by Helloman892** [comment]
Do you know what the QR scanner does? It only downloads the theme/splash, it doesn't apply it.

There's no need to be so hostile.

**Comment by coggrindder** [comment]
Your response seemed hostile to me, just a toss at my "ineptness".

I understand what the qr scanner does, and its functionality is broken when
trying to install splashes. I have also tried manually FTP the zip file
into /splashes and its the same.

**Comment by Helloman892** [comment]
To clarify, you're on the latest version of Anemone, yes? There've been a couple weird things happening recently, but they've been pinned down to old bugs.

It was not intended to comment at all whether you're inept or not - at the end of the day, I can't help if I'm not sure what the process is.

**Comment by XpertYoungen** [comment]
ive tried everything you said but they either don't show up at all or they show up under themes and give me an error when i click on them

**Comment by Helloman892** [comment]
They should definitely not be showing up under `Themes`. As I said before, make sure you're in splash mode *before* you activate the scanner.

The error will be because `body_LZ.bin` doesn't exist for a splash.

**Comment by XpertYoungen** [comment]
i am in splash mode but they still end up in themes

**Comment by Helloman892** [comment]
I cannot replicate this, at all - in fact, I will never be able to. The path that the QR scanner sends downloads to is intrinsically related to the mode that you're in, so again, I ask - Are you opening Anemone, pressing L to switch to splash mode, and then R to open the QR scanner?

**Comment by XpertYoungen** [comment]
Yes i am, it says no splashes found and when i scan one they still dont show up

**Comment by Helloman892** [comment]
Ah! That may explain it. Could you copy one of the splashes that isn't working from `/Themes` to `/Splashes` with FBI (or your PC, doesn't matter), and then try again?

**Comment by XpertYoungen** [comment]
Still nothing :(

**Comment by Helloman892** [comment]
Wait, so nothing shows up in splash mode?

**Comment by XpertYoungen** [comment]
nope

**Comment by Helloman892** [comment]
Two things:
1. Are you using the CIA version? If no, you're out of luck - splashes don't work on 3DSX.
1. Have you tried reinstalling? If no, please do.

**Comment by XpertYoungen** [comment]
i installed it through the qr code and ill try reinstalling it now

**Comment by coggrindder** [comment]
Yes, helloman, I am on latest. I reinstalled through titlesdb and it still gives just colored box w black preview screen.

**Comment by Helloman892** [comment]
>titledb
That's may be the issue - TitleDB is a bit messed up right now. Could you try deleting the title from FBI, and installing it via the QR code on the releases page?

Also, if it's not too much trouble, could you unzip the splash into a sub-directory under `/Splashes`? I have a feeling that there is a problem with the ZIP handling.

**Comment by coggrindder** [comment]
I do not see a releases page unfortunately

**Comment by coggrindder** [comment]
Nvm, reinstalled. Let's see if it works

**Comment by coggrindder** [comment]
Unzipping under splashes didn't fix the issue. Dratz

**Comment by Helloman892** [comment]
The releases page is linked on the front page of the repo - but here: https://github.com/astronautlevel2/Anemone3DS/releases

**Comment by Helloman892** [comment]
Does this only apply to one specific splash?
Also, according to my good friend @LiquidFenrir, this was fixed by complete accident in a recent rewrite. 
![image](https://user-images.githubusercontent.com/1565516/33672509-44e99b70-daa2-11e7-82dd-44b5592a2696.png)
Could you try installing this build, and see if it fixes it?

**Comment by coggrindder** [comment]
Every splash so far. Also, that QR gives me a "bad data" error

On Dec 6, 2017 10:27 AM, "Dylan G." <notifications@github.com> wrote:

Does this only apply to one specific splash?
Also, according to my good friend @LiquidFenrir
<https://github.com/liquidfenrir>, this was fixed by complete accident in a
recent rewrite.
[image: image]
<https://user-images.githubusercontent.com/1565516/33672509-44e99b70-daa2-11e7-82dd-44b5592a2696.png>
Could you try installing this build, and see if it fixes it?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/astronautlevel2/Anemone3DS/issues/102#issuecomment-349693485>,
or mute the thread

**Comment by coggrindder** [comment]
Hey @Helloman892 the build worked, but, previews do not work. Preview either doesn't show anything or shows last image from previous preview, ex: I oreviewed my current theme (minimalist pokeball)  and then attempted to preview a splash (ilex forest) and it showed my theme instead. I was in splashes at the time of second preview.

**Comment by LiquidFenrir** [comment]
Hm, that's not normal. Could you upload a zip of your /Splashes and /Themes for testing?

**Comment by coggrindder** [comment]
[https://mega.nz/#F!c6RFxSxY!W5XQinu5IvaPK_wMoPKDnQ] (url)
And
[https://mega.nz/#F!16JwAa4a!gIYtU9TtMDgc8doT_HcehQ] (url)

**Comment by LiquidFenrir** [comment]
Indeed, there's a problem in the logic, because the splash doesnt have a preview. this could even cause a crash if you're unlucky.
Fixed with c1ef601c2f7ac38db14b16e368e3c4efede3c7e6

**Comment by coggrindder** [comment]
Sweet. Any way to download this commit?

**Comment by LiquidFenrir** [comment]
Sure, [zip with the .3dsx and .cia here](https://github.com/astronautlevel2/Anemone3DS/files/1540138/out.zip)

**Comment by coggrindder** [comment]
Hey gents, no luck with that commit. Same issue.

**Comment by LiquidFenrir** [comment]
...what was the original issue again? Reading up it seems a bunch of different ones got mixed in this.
If it's the splashes downloaded by QR showing up in the themes and not the splashes:
- quadruple check you are in splash mode before downloading
- try deleting the splashes folder and recreating it, with a computer/fbi/godmode9

**Comment by coggrindder** [comment]
So, currently, its that the preview for splashes isn't functioning. I can install them and they work, but, when I preview them it either shows a black screen, a previous screen, or a "no preview found"

**Comment by LiquidFenrir** [comment]
"no preview found" -> the splash doesnt have a preview.png
black screen -> you pressed Y twice, without attempting to see another preview before (that worked)
previous preview -> you pressed Y twice, but tried another preview before (and it worked)

can you confirm that? If yes, they might have corrupted preview.png files

**Comment by LiquidFenrir** [comment]
QR code to a .cia with fix
<img src="https://cdn.discordapp.com/attachments/366999300594728960/389423505424515094/unknown.png" height=250 width=250/>

**Comment by astronautlevel2** [comment]
Closing issue after no response for > 10 days, will reopen if OP responds.
