### ISSUE TITLE
Need a START glyph to replace the wii "plus"

### ISSUE THREAD

**Issue by LiquidFenrir** [astronautlevel2/Anemone3DS#107]
Asking @Wizzrobes since he made the one for select
Since, with #106 START being quit is also displayed, this should cause the same troubles as SELECT did before, we should get rid of it right now

**Comment by Wizzrobes** [comment]
Sure thing, will make one immediately. Sound good to make a PR with the file in romfs? That way you can take care of the code for your new menu.

**Comment by LiquidFenrir** [comment]
Sure! Anything should be okay as long as it fits with the other

**Comment by Wizzrobes** [comment]
Alright, PR is up. Simply added the PNG, I'll let you take care of the code. New controls look good, just a bit over my head to totally understand :)

**Comment by LiquidFenrir** [comment]
thank you, it's consistent now!
