### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by ganondorf03** [astronautlevel2/Anemone3DS#115]
Hello! Anemone don't work on my New 3DS! et block on blackscreen with marked "homebrew"

My N3DS is up to date with luma up to date too.

**Comment by LiquidFenrir** [comment]
Bonsoir, combien de thèmes/splashes as tu dans les dossiers `Splashes` et `Themes` sur ta carte SD ? Si il y en a beaucoup, c'est peut-être juste que l'application prend longtemps pour tout charger.

Sinon, retélécharge Anemone ici: https://github.com/astronautlevel2/Anemone3DS/releases/download/v1.2.2/Anemone3DS.cia
puis installe le cia avec FBI, et essaye encore.
Il y a une chance que ce soit juste un téléchargement corrompu.

**Comment by ganondorf03** [comment]
Belfore I Washington usine themely and i have lots of themes but when it Washington on the blackscreen, no button respond, I must shutdown thé 3ds by forcing it with thé power button pushed 15 seconds.

**Comment by LiquidFenrir** [comment]
Malheureusement Anemone3DS prend du temps pour charger tous les thèmes avant d'afficher quoi que ce soit.
La seule chose que tu peux faire pour le moment est attendre que ça finisse de tout charger, attendre la mise à jour qui introduira le chargement dynamique (l'interface chargera les thèmes petit à petit), ou utiliser Themely. Désolé!
Et, juste pour mettre à jour le livre des records, combien tu as de thèmes exactement?

**Comment by ganondorf03** [comment]
I try this and it's good. It's working. Thanks
