### ISSUE TITLE
Closing app using home menu triggers exception

### ISSUE THREAD

**Issue by OctoNezd** [astronautlevel2/Anemone3DS#12]

**Comment by astronautlevel2** [comment]
Can you provide the crash dump?

Also, can you describe what you were doing to get this - 3dsx version or cia version, whether or not you installed any themes, etc.

**Comment by OctoNezd** [comment]
Cia.
You can crash app in any case(installed theme or not). Press home button, than click on "close".

**Comment by LiquidFenrir** [comment]
seems like a good use case for the home button block some games have. no idea how to use it from homebrew though

**Comment by astronautlevel2** [comment]
I know themely does it so it should be pretty easy to look into. 

Also, I actually can't replicate this on my own console, oddly enough. I'll keep this issue open for now though

**Comment by OctoNezd** [comment]
Weird, it stopped to crash.
I have no idea why it stopped crashing, I didn't deleted any themes, changed settings...

**Comment by OctoNezd** [comment]
Seems like it is random crash.
App sometimes close, and sometimes crashes.
I will upload crash dumps soon

**Comment by OctoNezd** [comment]
https://yadi.sk/d/wKxzCwWl3MXK3D
there

**Comment by astronautlevel2** [comment]
This has been fixed in 4084408562b22f0e43bbe3cb9ffdb98b39fe13eb
