### ISSUE TITLE
Suggestion: "Recycle Bin" (no, I'm not telling the dev to trash the project.)

### ISSUE THREAD

**Issue by sks316** [astronautlevel2/Anemone3DS#130]
Ok, so this is a bit of an odd suggestion. My idea is that whenever you "delete" a theme, instead of being gone permanently, it's instead moved to a sort of "Recycle Bin" where the file is retained for at least 24 hours before being automatically deleted. The user would be able to restore the theme or permanently delete it from within the Recycle Bin.

**Comment by Helloman892** [comment]
I can see a couple of ways to do this, but there is no way that we could delete the files without the app being launched.
