### ISSUE TITLE
QR Codes not working on N3DSXL

### ISSUE THREAD

**Issue by Rainmaker0102** [astronautlevel2/Anemone3DS#131]
On homebrew launcher, when going to take a qr scan I get a black screen on top with blue bar that says "hold R to go back."

On latest for Anemone, but is it because homebrew launcher doesn't have access to camera?

**Comment by LiquidFenrir** [comment]
Are you sure your camera isnt broken? It should only stay black for about 2 seconds, at least it's what happened for me just now with latest release (n3ds regular)

**Comment by astronautlevel2** [comment]
Camera requires CFW to use.

**Comment by Rainmaker0102** [comment]
Ok, thanks!
