### ISSUE TITLE
Shuffle Install with Two Single Themes can Corrupt Theme Management Extdata

### ISSUE THREAD

**Issue by TurdPooCharger** [astronautlevel2/Anemone3DS#134]
This bug was discovered on a US N3DSXL while figuring out Issue #132. Folder naming scheme subject to change depending on 3DS region of origin.

1. Take a spare 4 GB SD card. Format it in FAT32 and 32 KB cluster size. (Recommended)
2. Add in **3ds** (with _Anemone3DS.3dsx_), **boot9strap**, **exception_dump_parser**, **luma** folders.
3. Add in _boot.firm_ [Luma3DS], _boot.3dsx_ [Homebrew Launcher]
4. Add in **Themes** folder with two themes. Safely eject SD card.
5. Remove and reinsert 3DS battery. Insert SD card into 3DS. Turn on 3DS.
6. 3DS will create **HOME Menu management information**.
	- **Nintendo 3DS** folder is created. Within that folder, **0000008f** folder is created.
7.  Open **HOME Menu Settings**. Open **Change Theme**.
8. 3DS will create **theme-management information**.
	- Within **Nintendo 3DS** folder, **000002cd** folder is created.
9. Open **Shuffle Favorites**, select all five basic color themes. Press **(Y) OK**.
10.  3DS will update **theme-management information**.
	- Within **000002cd/00000000** folder, _0000000a, ...b, ...c, ...d, ...e, ...f_ files are created.
11. Open **HOME Menu Settings**. Open **Change Theme**. Select **Do not use a theme**.
12. Launch **Anemone3DS**. Press (B) on only the first theme. Do a **Shuffle install**.
13. Press (B) on only the second theme. Do a **Shuffle install**.
14. Press (Start). Turn off 3DS. Turn on 3DS.
15. Congratulations, your 3DS is now bricked.
	- Booting into Home Menu only has black screens of death.
	- You can try Recovery Mode with working LCDs but this does nothing.
	- Removing and reinserting the battery does nothing.

_**Luckily, this can be fixed.**_
16. Remove SD card from 3DS. Open SD card on computer.
17. Delete the **Nintendo 3DS** folder (if you don’t have games installed).
18. If you have games installed, rename your corrupted **Nintendo 3DS** folder.
19. Safely eject SD card. Insert SD card into 3DS. Turn 3DS on.
20. Ta da! Your once bricked 3DS is now functional again.
21. 3DS should now boot into Home Menu and rebuild **HOME Menu management information**.

22. Turn off 3DS. Remove SD card. Open SD card on computer.
23. Go to your good **Nintendo 3DS/[scramble #1]/[scramble #2]/extdata/00000000/** folder.
24. Open **00000082 (JPN)**, **0000008f (USA)**, or **00000098 (EUR)** folder.
25. Open **00000000** folder. Copy _00000001, ...2, and/or ...3_ file(s). You only need just one of these.
26. Go to your corrupt **Nintendo 3DS** folder and replace the respective file(s) with the clean version(s).
27. Delete 2nd **Nintendo 3DS** folder. Rename back the original.
28. Safely eject SD card. Insert SD card into 3DS. Turn 3DS on.
29. Not only is your 3DS working, all your games are intact.

For your next version of Anemone3DS, you devs be sure to fix **Shuffle install** with a install minimum of two themes. Toodles.

**Comment by ev1l0rd** [comment]
@TurdPooCharger - The 'brick' you are experiencing isn't a brick. It's due to invalid theme data being written to the home menu extdata. It can be resolved by removing the theme extdata. Please refer to the screenshot I attached below for how to do this:

![image](https://user-images.githubusercontent.com/13433513/35477706-b4a449ba-03c9-11e8-9298-0ff243424a3e.png)

Running CFW on sysNAND as long as you either have arm9loaderhax or boot9strap (ideally boot9strap) should be completely secure, as it's possible to recover from most software related bricks with it. emuNANDs should be considered obsolete for the end user.

**Comment by TurdPooCharger** [comment]
Did you not read the part where you program can cause this problem to appear? You guys need to change Shuffle install so that a minimum of two themes are installed, so that it makes it not possible to have that happen. If you guys leave it open like that, that's bad programming on your part.

Also, Issue #132 is separate from this one. I was just checking in to let you know that Anemone3DS works with 64 KB cluster with some work done to it. I know it's something your app wasn't meant to work with. Also, if you read my post, I was explaining why I was testing those cards in 64 KB.

**Comment by Helloman892** [comment]
We're aware that Anemone can cause improper theme management extdata to be written, and it's being fixed for the next release. For now, you'll have to put up with it.

Also, ev1l0rd isn't an Anemone developer and this therefore isn't his app. His response was entirely appropriate (if a tad passive-aggressive) considering the long and convoluted 'fix' you provided.

**Comment by astronautlevel2** [comment]
Can we all calm down a few notches? There's a lot of unneeded hostility in this thread.

I'll work on fixing this bug in the future, but for right now I'm extremely busy with school and real life - I can't promise it'll happen anytime soon.

**Comment by TurdPooCharger** [comment]
* My apologies. I'm not trying to be disrespectful. Kinda tired here. Alright, thank you for telling me that not everyone here is dev. Not trying to point fingers. We all have lives. Kinda sucks getting cold greetings when you try to write a proper documentations, but okay. We cool?

**Comment by astronautlevel2** [comment]
Aaand of course, LiquidFenrir manages to beat me to it, as usual.

Closing this since the latest commit should fix it.

**Comment by LiquidFenrir** [comment]
Would you mind testing this cia? It should fix this. Let me know if it doesnt work.

<img src="https://cdn.discordapp.com/attachments/366999300594728960/406971711678840832/unknown.png" height=250 width=250/>

**Comment by TurdPooCharger** [comment]
Just to be clear, you guys want me to test the Shuffle install with single themes, and not if this works on 64 KB?

**Comment by Helloman892** [comment]
This pertains only to this issue in particular, yes.

**Comment by TurdPooCharger** [comment]
Sorry if I'm a bit slow in coming back with results.

![nice](https://user-images.githubusercontent.com/35666439/35477948-f6348d9e-039d-11e8-9ea1-00a653cfdd45.png)

Nice. It gets my approval. Thank you.

**Comment by LiquidFenrir** [comment]
Thank you! It's now considered fixed, comment again if you find the problem occurs
