### ISSUE TITLE
Shuffle themes without BGM

### ISSUE THREAD

**Issue by mehlon** [astronautlevel2/Anemone3DS#136]
Some themes have an annoying background music, so it'd be nice if one could shuffle multiple themes without BGM. Ideally, here's what I want to be able to do: Shuffle multiple themes without BGM, then install a single theme BGM-only, so all themes effectively have the same music.

**Comment by TurdPooCharger** [comment]
Hey, I know this isn't a clean solution to your problem but there is a way to get your 10 theme shuffle to have the same BGM.

1. Rename your 'Themes' folder into 'Themes (main)'.
2. Make a new blank 'Themes' folder.
3. Make a copy of the 10 themes from the main collection and move them over to the new 'Themes' folder.
4. Copy and replace the 'bgm.ogg' sound files with the one you want to hear.

This isn't quick to do especially if you have a lot of themes, but it will get the job done for the time being.

**Comment by LiquidFenrir** [comment]
bgm.bcstm is the file used for bgm, so it is the one you should copy, not bgm.ogg.
