### ISSUE TITLE
After installing a custom theme I can only use 4 Vanilla Themes to shuffle through

### ISSUE THREAD

**Issue by FusselTeddy** [astronautlevel2/Anemone3DS#137]
Hello there :)

I'm glad that we wre able to install custom Themes, but now I want to shuffle through my old vanilla Themes again. But every time I want to select all of them, some blank Themes block the first 6 Slots of the vanilla theme shuffler. Is there anything I could do to solve this?

**Comment by LiquidFenrir** [comment]
Let me take a guess, you had 6 custom themes selected in shuffle mode? Try adding a vanilla theme to the shuffle, then press OK. it should say it was unable to do it, and reset the theme to default, then you can use any you want
