### ISSUE TITLE
Folders

### ISSUE THREAD

**Issue by Konngitas** [astronautlevel2/Anemone3DS#138]
Add support for folders to organize themes inside the application. Structure coincides with the directory structure of Themes/Splashes in the SD card, to also allow organization from outside the application.

**Comment by Helloman892** [comment]
The way I recall it, the reason we didn't support this from the start was to maintain backwards compatibility with Themely - people could switch between the two at will without any worry. However, this (at least, the backend for it) shouldn't be too difficult to write. If I finally get off my ass and do something useful, I might take a stab myself - unless @LiquidFenrir wants to do it?

**Comment by Konngitas** [comment]
@LiquidFenrir disliked my suggestion for being "too hard to implement", although I believe the backend for this would not be difficult to write either. I am willing to contribute to this, and might start work on it soon if no one does before me.

**Comment by LiquidFenrir** [comment]
Would be hard/slow to implement without dropping support for folder themes, but fairly easy if we do. Just thought anemone's focus was backwards compatibility

**Comment by Konngitas** [comment]
Can you explain your reasoning for that? I dont think it would be hard if we kept support for folder themes. It is not worth it dropping folder theme support just for this anyway

**Comment by LiquidFenrir** [comment]
well, you would need to check if every single folder is a theme/splash or not, and that can get slow pretty fast. dont really have any other arguments in mind

**Comment by Konngitas** [comment]
That is what I was thinking would have to be done, but I did not know it would slow things down so much

**Comment by LiquidFenrir** [comment]
well it most likely wouldnt be that bad for everyone, but considering several people have thousands of themes, I'm sure at least 1 person will experience visibly slower load times :p

could definitely be useful though

**Comment by Konngitas** [comment]
Probably! But its especially for those people that have thousands of themes that these folders would be useful! Then again even just having thousands of themes would slow things down considerably no? You are checking 1000 folders. Whats the difference between 1000 and 1000 plus a few for organizing?

**Comment by astronautlevel2** [comment]
Won't really work with the current design of Anemone, maybe in the future it can be reconsidered after some large structural changes.
