### ISSUE TITLE
'Your camera seems to have a problem, unable to scan QR'

### ISSUE THREAD

**Issue by firewolfgames** [astronautlevel2/Anemone3DS#139]
Title.
Also that text is cut off and shows like "-ur camera seems to have a problem. unable to scan Q-"

**Comment by Helloman892** [comment]
First, are you using the 3DSX version? If so, are you using *hax Homebrew Launcher (no custom firmware) or Rosalina HBL (Luma3DS)?
Secondly, graphical errors happen an awful lot with text. At this point I'd just ignore it - all the message means is that whatever is hosting your Homebrew Launcher has no access to the cameras.

**Comment by firewolfgames** [comment]
I was expecting it was something with userland restrictions, getting closer to getting cfw though, so that shouldn't be a problem
