### ISSUE TITLE
Bottom screen icons display incorrectly in splash mode

### ISSUE THREAD

**Issue by Seddigirl** [astronautlevel2/Anemone3DS#144]
I'm using beta 2.0.0a
![2018-04-04_10-24-50 388_bot](https://user-images.githubusercontent.com/14105847/38299695-1fffb41e-37fb-11e8-9b54-35be0c39af01.png)
let me know if you need any more info (i didnt really know what to include)

**Comment by LiquidFenrir** [comment]
check the top screen...this happens because you dont have any splash in `/Splashes`. but will fix, it's indeed a problem

**Comment by LiquidFenrir** [comment]
Thanks for reporting, completely forgot to update this screen :)
Try it out:
<img src="https://cdn.discordapp.com/attachments/366999300594728960/431026835187433473/unknown.png" height=300 width=300 />

**Comment by Seddigirl** [comment]
yep its fixed :+1:
