### ISSUE TITLE
Spanish translation?

### ISSUE THREAD

**Issue by pilladoll** [astronautlevel2/Anemone3DS#15]
Great app! Fast, and simple.

Only thing I need is a spanish translation to make things more easier <3

**Comment by astronautlevel2** [comment]
Translations are definitely a planned feature!

**Comment by pilladoll** [comment]
I can help you with the translation =)

**Comment by Juanito9001** [comment]
I can help too with the translation, i speak mostly spanish (mostly: i think that's the word for in this case: hablo mas que todo español)
in other case... sorry for my english

**Comment by astronautlevel2** [comment]
Closed (#80)
