### ISSUE TITLE
Constant Crashes

### ISSUE THREAD

**Issue by satoru8** [astronautlevel2/Anemone3DS#152]
Doesnt seem to matter what I do. Anything and everything results in a crash. Maybe something simple that I overlooked. Heres the logs...

[Anemone Logs.zip](https://github.com/astronautlevel2/Anemone3DS/files/1942245/Anemone.Logs.zip)

**Comment by astronautlevel2** [comment]
Can you provide more information?

What version of Anemone3DS are you using, when do the crashes occur (could you describe each of the ones you sent in the zip), what console version you're on, what CFW you're using, etc.

Thanks!

**Comment by shinji257** [comment]
I'm using 2.0.0 and getting some random crashes on ARM11.  At least twice when trying to use the qrcode to download and then once during the preview.  Here are the crash dumps that I have for this.

https://www.dropbox.com/s/9qv5gy9ervcev7w/Anemone.zip?dl=0

**Comment by shinji257** [comment]
Just wanted to let you know that I self-compiled a build from the repository source and the fixes seem to be working for me.  Checked both previews and downloading.
