### ISSUE TITLE
Anemone Crashing

### ISSUE THREAD

**Issue by Arsse** [astronautlevel2/Anemone3DS#154]
Anemone is crashing when I shuffle themes. It only seems to happen when I do more themes; getting closer to the 10/10 mark. I have a few crash dumps saved if posting them would help.

**Comment by LiquidFenrir** [comment]
If you were using the pre release v2.0.0a, it would indeed help if you posted the crash dumps, if you still have them, that is.

**Comment by astronautlevel2** [comment]
Will open again if OP responds with crash dumps.
