### ISSUE TITLE
Slight issue, anemone and Naruto SD Powerful Shippuden share the same title id

### ISSUE THREAD

**Issue by RandomMan25XX** [astronautlevel2/Anemone3DS#160]
Anemone has the same title id as Naruto SD Powerful Shippuden, both of which are 00040000000AFE00, while it isn't an issue for me personally, anyone with this game installed as a cia rather than just using the cart may have it overwritten by Anemone, and anyone that uses nanquitas' luma plugin loader with cheats for the aforementioned game will encounter a crash as the plugin loader if not disabled will attempt to load the cheat file when running anemone without first disabling the plugin loader

**Comment by TurdPooCharger** [comment]
Which region of Naruto SD Powerful Shippuden?

**Comment by astronautlevel2** [comment]
I'm not entirely sure what the best way to handle this is.

Obviously the TitleID needs to be changed. However, the issue with that is there will be two copies of Anemone3DS.

Maybe introduce code that will remove the application at 00040000000AFE00 if it's present and its product code is CTR-P-ANEM? That way we can minimize the amount an end-user needs to do.
