### ISSUE TITLE
Using QR code to download Splashes and Themes crashes the console

### ISSUE THREAD

**Issue by jakeramsay007** [astronautlevel2/Anemone3DS#161]
Utilising QR codes to download from themeplaza crashed the arm11 with a data abort exception. The themes and splashes still were downloaded and could be used after turning the console (3dsXL) back on after the hard crash.

Crash dump: https://www.dropbox.com/s/vpbvkztzvqqu9xq/crash_dump_00000000.dmp?dl=0

**Comment by astronautlevel2** [comment]
This has been fixed in 1c3e8809f685f1204244ebf77a40bcdd34dd2b93.
