### ISSUE TITLE
Homebutton not working right

### ISSUE THREAD

**Issue by Flik210** [astronautlevel2/Anemone3DS#163]
Using the cia:
Pressing the home button in the "main menu" seems having no effect. 
In the theme browser on the other hand it works normaly. 
But when i try to exit anemone through the home button, the 3ds freezes at this software closing screen. Only hard reset or reboot through rosalina menu helps.

I now i should exit anemone with the Start button, but i guess this is still a bug of some kind.

**Comment by LiquidFenrir** [comment]
You're not supposed to use the home button at all, only start or power. but yes, it being usable in the browser is a bug, thank you
