### ISSUE TITLE
prepackaged Theme Plaza icon cache

### ISSUE THREAD

**Issue by TurdPooCharger** [astronautlevel2/Anemone3DS#166]
Sorry for missing and opening the other issue. 

I'm not sure if you're down for this idea. Would you like to host this, or can you get in contact with the Theme Plaza admins in doing a quick cache download feature for Anemone? If that's not technically possible or impractical to implement, here's the entire (current) collection of theme icon cache scrapped last night.

I made a post about this at the GBAtemp thread earlier but don't feel where it's currently hosted is appropriate.

[Anemone_ThemePlaza_icon_cache.zip](https://github.com/astronautlevel2/Anemone3DS/files/2000913/Anemone_ThemePlaza_icon_cache.zip)

**Comment by astronautlevel2** [comment]
I see no reason to do this when the current cache is working as well as it is.

**Comment by TurdPooCharger** [comment]
It takes a while to download the icon cache when you explore for new themes in Theme Plaza mode. It becomes increasingly slower the more themes you try to view as Theme Plaza server starts to throttling your download in building the cache.

Having it preinstalled in the 3ds/Anemone3DS/cache folder reduces the waiting, giving a faster experience in seeing more themes. :)

**Comment by astronautlevel2** [comment]
ThemePlaza doesn't throttle anything.

As of right now I'm happy with the current behaviour and don't want to change anything.
