### ISSUE TITLE
Certain themes can crash when previewed in Theme Plaza browser

### ISSUE THREAD

**Issue by TurdPooCharger** [astronautlevel2/Anemone3DS#174]
After previewing thousands of themes in Theme Plaza browser, these are the three types that will cause a crash or freeze. I provided single examples for each category. If you need more themes to verify for the three types, I can list more.

## Type 1 - bgm.ogg does not exist or has a file size of zero.

**Description:** This is the most common of the three listed here. You can preview one of these themes per a single session. When you exit out the preview with (Y), you either crash or will crash when you preview that same theme again or a different theme.

**Cache & Log Dump:** [Crash Type 1 - no bgm.ogg.zip](https://github.com/astronautlevel2/Anemone3DS/files/2052680/Crash.Type.1.-.no.bgm.ogg.zip)

**Theme Link:** https://themeplaza.eu/item/6777

![6777 - loekaars custom theme](https://user-images.githubusercontent.com/35666439/40703820-6f275eea-63b4-11e8-89d3-113dbd7ca27b.png)

***

## Type 2 - bgm.ogg is mono type.

**Description:** This one reacts much the same way as type 1. 

**Cache & Log Dump:** [Crash Type 2 - bgm.ogg (mono).zip](https://github.com/astronautlevel2/Anemone3DS/files/2052681/Crash.Type.2.-.bgm.ogg.mono.zip)

**Theme Link:** https://themeplaza.eu/item/6494

![6494 - kingdom hearts - winnie the pooh](https://user-images.githubusercontent.com/35666439/40704881-6dc2bbaa-63b7-11e8-8e93-7e63f831f18a.png)

***

## Type 3 - The theme's title or description has the char ō displayed as ▮.

**Description:** This is the rarest of the three. I've only found themes of this type made by a single author, oOlzZiSslOo. He has several Japanese based themes with the letter o accented with the macron.

Nothing seems out of the ordinary for the cache files for themes titled with the char ō. These can be previewed with working sound. They sometimes crash or freeze when you exit out of preview but this isn't always the case. Previewing even just one of these themes with ō/▮ in its title or description tends to cause Anemone to crash/freeze after previewing several other themes.

**Note:** For type 3, I was not able to retrieve a log dump of this type on my 4 GB test build as it only experienced menu freezes. This log dump comes from my 128 GB/64 KB normal build; Anemone .3dsx version was used in both setups.

**Cache & Log Dump:** [Crash Type 3 - Title with char ō.zip](https://github.com/astronautlevel2/Anemone3DS/files/2052822/Crash.Type.3.-.Title.with.char.o.zip)

**Theme Link:** https://themeplaza.eu/item/6512

![6512 - mondaiji-tachi ga isekai 01](https://user-images.githubusercontent.com/35666439/40705236-52b88a96-63b8-11e8-9b01-4f184a6ac049.png)

**Comment by astronautlevel2** [comment]
Not sure what to do about number 3, number 2 I can take a look at later but number 1 should be fixed with this QR code:

![QR](https://cdn.discordapp.com/attachments/433305322560684043/452306609411063818/Anemone3DS.cia_qr.png)

**Comment by astronautlevel2** [comment]
You said you tried testing - did it work? It is a dev build, but ignore the version number weirdness.

**Comment by TurdPooCharger** [comment]
On break from yard work due to rain. 

That build has this strange behavior where it won't play bgm for previous themes in ThemePlaza.

- If you download the cache of a new theme for the first time, its bgm works.
- If you exit out of preview and preview that theme again, bgm still works.
- If you preview a second, new theme (for the 1st time) and go back to that first theme, it's bgm stops working.
- Only the newest previewed theme will retain working BGM, like passing hot potato.
- Backing out with (B) to go to Theme mode and then returning to ThemePlaza mode, the last theme does not lose its working BGM placeholder status.
- BGM hot potato gets dropped with that session of Anemone. 
- There are coding references and � appearing out of place like this:
![funky char](https://user-images.githubusercontent.com/35666439/40880554-482ba808-6681-11e8-966c-a9227c273712.png)
- Using the (Up, d-pad) + (X) page jumping borks scrolling. L/R shoulder navigation works until the moment page jumping is used. * I'll need to check this one again later on v2.0.1 as it could be a separate bug. It might be trying to page jump to a page you haven't visited with L/R scrolling. 
- Trying to exit out of Anemone with (Start) leads to a crash. 
[crash_dump_00000025.zip](https://github.com/astronautlevel2/Anemone3DS/files/2065307/crash_dump_00000025.zip)

And finally...
- Type 1 (no bgm) themes still crashes. 


Hey, let's pick this back up on Monday? I'm in the final stages of prepping my lawn. Tomorrow's the big day I plant grass seeds. Finger's crossed for green thumb.

**Comment by Helloman892** [comment]
@astronautlevel2 damnit man did you give him a build without proper parsing

**Comment by TurdPooCharger** [comment]
Oh what the heck, Microsoft is absorbing GitHub?

The ō letter is not Latin based but of Cyrillic origins. Funny enough, none of the major Slavic languages use that letter in their modern alphabets. If there's a Russian language option in the eastern European 3DS market, it might be found there as a holdover. There is an official Nintendo of Russia website but no indications of the 3DS firmware in Russian.

I tried renaming files to see how Checkpoint, FBI, and the 3DS browser handles displaying it.

![checkpoint](https://user-images.githubusercontent.com/35666439/40934868-340ee9b4-6804-11e8-94e4-3fa619f53872.png)

![fbi](https://user-images.githubusercontent.com/35666439/40935008-bed040c0-6804-11e8-9f7f-29485d20cab9.png)

![3ds browser o](https://user-images.githubusercontent.com/35666439/40934880-3d58f7a8-6804-11e8-8bd8-35c6ab0ec8f6.png)
 
Here's the current count for ThemePlaza's repertoire for Type 3 themes if it helps in assessing what to do for this one. There are 26 in total.

By oOlzZiSslOo
- Mondaiji-tachi ga Isekai # 01 - 04
- Kyōkai no Kanata # 01 - 03
- Chūnibyō Demo Koi ga Shitai! # 01 - 08
- Shokugeki no Sōma # 01 - 10

By empoleon434
- Susari - Suprise Party!

**Comment by astronautlevel2** [comment]
Number 1 and 2 should be fixed with https://github.com/astronautlevel2/Anemone3DS/commit/2dfa2e90ef310bd012f8a878c8da3ec0e9cd24c8

![QR Code](https://cdn.discordapp.com/attachments/433305322560684043/454074020451844107/Anemone3DS.cia_qr.png)

**Comment by TurdPooCharger** [comment]
- Testing was done on my 32 GB / 32 KB Samsung micro SD borrowed from my cellphone. It has about 28 GB of free space.
- The decision to not use my 4 GB card was due to the cache I amassed these past weeks. I was planning to do a sweep in ThemePlaza browser later.
- Barebone CFW setup with the exception that all my cellphone stuff were put in a separate file placed in root.
- The provided Anemone build was GodMode9 injected in StreetPass MiiPlaza. 
- The cache acquired through my installed v2.0.1 stable build was not used. 

**Battery Testing for Type 1**
6610 - Doki Yuri , :+1: 
6779 - Persona Q Sub-Persona screen , :+1: 
6941 - My Hero Academia - Deku Theme , :+1: 
6966 - Ash Basic (Black) , :+1: 
6967 - Ash Basic (Yellow) , :+1: 
**Result** - PASSED. These themes were reached by both L/R scrolling to their page and using the search feature.

**Battery Testing for Type 2**
6890 - Off - The Batter , :-1: 
**Result** - Incomplete. Theme 6890 was reached by using the search feature. It was previewed at least 3 times in semi-quick succession of (Y) button presses; I did not go crazy in rapidly tapping (Y). Crash dump states it was a kernel panic. 
[crash_dump_00000000.zip](https://github.com/astronautlevel2/Anemone3DS/files/2078723/crash_dump_00000000.zip)

**Comment by TurdPooCharger** [comment]
**Continued with Type 2 Testing** 
6494 - Kingdom Hearts - Winnie the Pooh , :+1:
6814 - Kale/Caulifla/Kefla , :+1:
6836 - The Seven Deadly Sins Theme , :+1:
6872 - A Time Traveler , :+1:
**Result** - These last four were searched. In the search results, I previewed neighboring themes alongside with them. No misbehavior with test session. 

Treat that panic kernel as a separate bug for the time being. It might have to do with something from downloading preview cache when transitioning between normal, Type 1, and Type 2 themes back-to-back. I was previewing the latest themes for the first four pages when it happened, downloading their cache for the first time. I'll let you know if I find a consistent way in triggering that crash.

**Comment by TurdPooCharger** [comment]
@astronautlevel2, I think I got something. When you get the chance, can you check on your end what happens when you do this? You don't have to delete the cache.

**Inducing Kernel Panic**  

1. Start up that dev build of Anemone and go to ThemePlaza mode.
2. Preview the 24 themes on the first page in [top-to-bottom/left-to-right] order starting at the upper-left corner. Make your way previewing themes going right.
3. Scroll to the next page or jump to any other page.
4. Preview another 15 or so themes, again by [top-to-bottom/left-to-right] order starting at top-left.
5. If crash does not occur at page 2's 15th theme, sometimes Anemone tries to redownload the preview's or bgm's for later themes. BGM might go silent if previewer works -or- previewer stops working altogether. 

I got a niece who's over at my place, and she brought her N3DS. I can try repeating this on her system later tonight.

**Comment by astronautlevel2** [comment]
It seems very hard to trigger the new bug that you've described, and a standard user probably won't run into it. In addition, I don't see anything obvious that could be causing it - however, I'm going to leave this issue open just in case I decide to take a look at it again later. For now, don't get your hopes up about it being fixed.
