### ISSUE TITLE
Option to shuffle all themes

### ISSUE THREAD

**Issue by benjisora** [astronautlevel2/Anemone3DS#178]
Hi, I'm using Anemone3DS and am extremely happy with the results and easy-to-use theme management tool, good job on making it so intuitive so far !!

However, could it be possible to add the option to shuffle-install all themes available instead of just 10, or would it be not recommended to get rid of that limit due to what's being done in the background by the software ?

Thank you,

**Comment by ihaveamac** [comment]
10 themes is the limit Nintendo put into the HOME Menu, so this can't be done.

**Comment by benjisora** [comment]
Ahh, it makes sense... too bad then ! Thanks for the fast answer, closing this :)
