### ISSUE TITLE
All updates that i would wish(and maybe bugs that i found)

### ISSUE THREAD

**Issue by YTElias** [astronautlevel2/Anemone3DS#18]
Tested on .3dsx 
Updates(5)
An Auto Updater(already in prograss Thanks)
~~Deleting splash.bin(dont know is it in progress?)~~ done
Web browser(also in progress)
Like themely a preview already avaible on the top
~~QR Code like we want it or?~~ done

Now Bug(1)
When I install the bgm from a theme(i take the overwatch one) and want to change it back i cant
the only move to reset it is to have a blank home menu(Themes--Standart Home menu

Also You doing a great project im gonna say this has potential 
Good night or day whatever

**Comment by ZetaDesigns** [comment]
The bug you found should be fixed, try the latest release
