### ISSUE TITLE
Shuffling Themes does not work

### ISSUE THREAD

**Issue by Rosquash** [astronautlevel2/Anemone3DS#182]
After queuing 10 themes, holding A then Down then releasing A to install it, when I press start to return to the home menu, it does not work.

**Comment by astronautlevel2** [comment]
Did you make sure to restart after installing shuffle

**Comment by Rosquash** [comment]
Yes. It seems to not work only when queuing all 10 themes. I tried with 8 and it worked.

**Comment by TurdPooCharger** [comment]
@Rosquash, what version of Anemone3DS are you using?

**Comment by Rosquash** [comment]
The latest version

**Comment by TurdPooCharger** [comment]
These instructions were copied and simplified from a different GitHub issue that dealt with misbehaved theme shuffle from an previous version of Anemone. 

This version of the guide hasn't been tested for the newer releases. I make no guarantee if this will work for you, @Rosquash.

## Fixing the Shuffle Install for Anemone3DS (v2.0.0 and newer) 
1. By computer, go to the **Nintendo 3DS/<'ID0'>/<'ID1'>/extdata/00000000/** folder on your SD card.
2. Delete the **000002cd** folder. This folder contains your **theme-management information**.
3. Safely eject the card, reinsert it back to the 3DS, and turn the system on.
4. On the top-left corner of the bottom screen, open **HOME Menu Settings**. Open **Change Theme**.
5. The 3DS will create **theme-management information** with this message:
   -  Within the Nintendo 3DS folder, the **000002cd** folder will be recreated.
![create_theme](https://user-images.githubusercontent.com/35666439/35471371-ea3903d8-0327-11e8-8181-fb64df6f1b17.png)
6. Open **Shuffle Favorites**. Select all five basic color themes. Press **(Y) OK**.
7. The 3DS will update **theme-management information** with this message:
![update_theme](https://user-images.githubusercontent.com/35666439/35471373-f55368d0-0327-11e8-9ba3-80e429330792.png)
8. Open **Anemone3DS** either in **Homebrew Launcher** -or- in its stand-alone CIA version.
9. Press (B) to select 10 themes. Do a Shuffle install using (A) and (Down, d-pad). 
10. Restart the 3DS by pressing the (Start) or (Power) button.

**Comment by Helloman892** [comment]
@Rosquash If the above worked, would you mind closing this issue? Otherwise, could you respond again? If no response is received within 48 hours of this post, I will close this myself.
