### ISSUE TITLE
[suggestion] slight tweaks for the HOME Menu banner

### ISSUE THREAD

**Issue by TurdPooCharger** [astronautlevel2/Anemone3DS#183]
**Backstory**
While browsing on GBAtemp, I found the user Vuples-Vulpeos created alternative banners, icons, and backgrounds for bubble2k16's emulators. He used Anemone as the template for his banners. 

https://gbatemp.net/threads/release-picodrive-for-3ds.493521/page-25#post-8110717

When trying to modify and recompile snes9x_3ds with his substitute images, I noticed his snes9x banner was a bit fuzzy around the edges. This lead me to go back and examine Anemone's original banner for comparison. After cross checking, I believe Anenome's banner has room for slight improvements.

***

[Proposed Banner.zip](https://github.com/astronautlevel2/Anemone3DS/files/2173338/Proposed.Banner.zip)

The banner in that archive is a modified PNG version from the v2.0.0a source code. I learned that the fixed _logo.bin_ made by FrozenChen from issue #146 does not share the same image as the one found in the banner. The banner has gradients versus the logo having a single solid blue color. In order to maintain faithful reproduction, the original banner was used a starting point.

Also included is a Photoshop .psd file for further examination. Steps were taken in recreating the blue rectangle (with the two 45-degree cut corners) while removing all the previous transparent pixels along the edges. The vertical blue gradient shift and center phrasing were kept intact. 

The edges were extended a further 1 or 2 pixels and their opacity dropped to 1%. These "invisible" edges were added as buffers to compensate for white color distortion and improper 3D rendering noises, especially along the left, right, and two notches.

For quickly checking on actual 3DS hardware, a CIA of the Anemone dev build provided in issue #174 was de/recompiled with the proposed banner. Without changing Title ID, the fastest way to get two copies of Anemone on HOME Menu is through Health & Safety injection and regular FBI installation. Banners should be A-B tested through a variety of themes including the 5 basic colors, dark-vs-light, shades of blues, and varying degrees of 3D depth perception.

If that proposed banner is satisfactory and up to standard, the _banner.bin_ and its decompiled files are in there for swift implementation.

**Other tools that were used:**
- bannertool v1.1.0 - [compile banner.bin]
- ba-GUI-nnertool v2.2 - [decompile banner.bin]
- GodMode9 v1.6.3 - [CIA encrypt & decrypt]
- HackingToolkit9DS v12 - [CIA decompile & recompile]

**Comment by astronautlevel2** [comment]
Open a PR with the changes and I'll be happy to merge them.
