### ISSUE TITLE
splashes help

### ISSUE THREAD

**Issue by AgentScarlet** [astronautlevel2/Anemone3DS#184]
how do i install splashes properly?? ive tried and dont seeem to get it going

**Comment by TurdPooCharger** [comment]
The GitHub issues page isn't for asking for help in figuring out how to use Anemone. This is meant to report encountered bugs and requests for suggested features/improvements. 

For future reference, ask for help at the Anemone official thread:

- [[RELEASE] Anemone3DS - A Complete Theme and Splash Manager for your 3DS!](https://gbatemp.net/threads/release-anemone3ds-a-complete-theme-and-splash-manager-for-your-3ds.482804/page-26)

***

Now that we have that out of the way, I'm assuming you were hit the "WARNING: Splashes are disabled in Luma Config" message when crossing over to Splash mode with the L-shoulder button and already having some splashes in the **Splashes** folder. To allow Anemone to install splashes, hold the (Select) button when you turn on the 3DS. You should boot into Luma configuration. Select either **Before (x)** or **After (x)** as seen below.

If this solves your problem, close the issue on your way out. If, on the other hand, you did the outlined steps and your problem still persists, please stay and feel free in further explaining in details whatever setback you experienced in case this warrants further investigating. Thank you.

![luma config splashes](https://user-images.githubusercontent.com/35666439/42695286-e3f5a3bc-8682-11e8-833f-5fe6cd35f080.png)

**Comment by Helloman892** [comment]
@AgentScarlet 
@TurdPooCharger is right, this isn't for general support;

@TurdPooCharger: Please refrain from answering on our behalf.

**Comment by AgentScarlet** [comment]
asked for help there. no response.  ty.  themely was easier to understand. least it came with instructions.

**Comment by astronautlevel2** [comment]
Instructions are on the github wiki/in-app. Issues are not for Q&A, and please refrain from responding to old issues for no purpose. Locking.
