### ISSUE TITLE
Preview freezing 3DS

### ISSUE THREAD

**Issue by Kelvao** [astronautlevel2/Anemone3DS#186]
The previews are freezing the 3ds, I open the preview with Y and the 3ds freezes

**Comment by Helloman892** [comment]
Have you tried pressing Y to close it again?

**Comment by Kelvao** [comment]
yes, I tested all the buttons and I can only get out holding the power button to force the shutdown of the Nintendo 3DS

**Comment by Helloman892** [comment]
Does this happen with every theme?

**Comment by Kelvao** [comment]
Yes! Every theme

**Comment by Helloman892** [comment]
... huh. I can't say i've ever seen this before.

**Comment by Helloman892** [comment]
Have you tried reinstalling Anemone? What version are you using (bottom left)?

**Comment by Kelvao** [comment]
I use version 2.0.1, I tried reinstalling using qrcode and manually downloading the .cia. Did not work

**Comment by Helloman892** [comment]
Bizarre. Well, until this can be corroborated, I can't say that this isn't exclusive to your console - could you see if ihaveahax's fork of Themely works?

**Comment by astronautlevel2** [comment]
@Kelvao Are you sure that you have your DSP Firm dumped? Use zoogie's DSP-1 app to make sure.

**Comment by Kelvao** [comment]
with Themely I had DSP1 error

**Comment by Kelvao** [comment]
Now works! Sorry about that :D
