### ISSUE TITLE
Anemone only recognizes Themes and Splashes folders in the root of the SD

### ISSUE THREAD

**Issue by DeathStarCommander** [astronautlevel2/Anemone3DS#188]
I want to put the Themes and Splashes folders Anemone needs in a subfolder, but it doesn't recignizes them and then creates the same empty directories.

I don't know if that's how it's suposed to work. If so, could it please be added as a feature??. If not, how can I make it work that way??  Thx ^^

**Comment by astronautlevel2** [comment]
This is part of a future plan for a config file. Closing as duplicate of #31.

**Comment by DeathStarCommander** [comment]
I see... Thanks :ok_hand:
