### ISSUE TITLE
Theme Shuffling causes app to crash.

### ISSUE THREAD

**Issue by smrtg** [astronautlevel2/Anemone3DS#190]
Trying to get themes to shuffle crashes the app and stops the process.

[crash_dump_00000002.zip](https://github.com/astronautlevel2/Anemone3DS/files/2336930/crash_dump_00000002.zip)

**Comment by smrtg** [comment]
1. I'm using v2.0.1 2. Luma3ds is my cfw. 3. As the installer changes to "installing shuffle theme" the app immediately crashes and goes to the crash report screen. 4. I tried many themes, ones I installed with QR codes, ones I installed through the theme market, even ones that I downloaded and added to the SD card, any more than 3 themes causes the installation to stop and the app to crash

**Comment by smrtg** [comment]
Beta works like a charm, the only two problems/changes that I could propose is a loading bar when installing shuffle themes, and when you reopen the app it should show you what themes you have installed

**Comment by astronautlevel2** [comment]
Thanks for testing and confirming it now works!
