### ISSUE TITLE
"Wii Theme Channel" theme bricked my 3DS

### ISSUE THREAD

**Issue by ecr960** [astronautlevel2/Anemone3DS#192]
So I downloaded a custom theme from ThemePlaza (https://themeplaza.eu/item/9989) willing to add it to my list of shuffling themes. Once the theme was randomly selected, it bricked my 3DS. I couldn't get it to work anymore, and it was stuck on that theme. How do I fix this?

**Comment by MarioMasta64** [comment]
you can try deleting the home menu extra data off the sdcard (which may clear a few other things as a side effect (like badges and stuff))

/Nintendo 3DS/<32-character-id>/<32-character-id>/extdata/00000000/<region>/

- EUR Region: 00000098
- JPN Region: 00000082
- USA Region: 0000008f
- CHN Region: 000000A1
- KOR Region: 000000A9
- TWN Region: 000000B1

**Comment by ecr960** [comment]
Thanks! It worked.

The only downside was that all my games and CIAs were all put outside their folders and now I have to reorganize them.
