### ISSUE TITLE
request: add a faq for people who get bad themes and soft-brick

### ISSUE THREAD

**Issue by MarioMasta64** [astronautlevel2/Anemone3DS#193]
add info like #192 for people who get bad themes as a fix suggestion (a faq on the readme page maybe) note that it will clear out home menu data so themes and badges and stuff will be reset (as seen in the issue)

**Comment by Helloman892** [comment]
This already exists at https://github.com/astronautlevel2/Anemone3DS/wiki/Known-Bugs.

**Comment by MarioMasta64** [comment]
👍
