### ISSUE TITLE
Blackscreen while booting

### ISSUE THREAD

**Issue by RedShyGuy** [astronautlevel2/Anemone3DS#194]
I don´t know if that is a already known problem but everytime I try to start Anemone I get a black screen   (it freezes) I tried several times to reinstall it (also tried different versions) but it wont work

**Comment by Garebear1903** [comment]
Me too. Is It Because I Have Themes From Nintendo Or What?!

**Comment by astronautlevel2** [comment]
What versions of Anemone have you tried, and how many themes do you have in your Themes folder?

**Comment by Garebear1903** [comment]
Nvm Just Forgot The .smdh, .elf, and .3dsx files to go into the 3DS folder.
