### ISSUE TITLE
Scroll crashes

### ISSUE THREAD

**Issue by RinMaru** [astronautlevel2/Anemone3DS#196]
New 3DS XL
Firmware- 11.8.0-41U
CFW- Luma 9.1/ Boot9Strap 1.3
Anemone3DS- 2.1.0-b

have about 71 themes and scrolling down or doing much of anything will crash the entire system

[Luma DMP.zip](https://github.com/astronautlevel2/Anemone3DS/files/2564824/Luma.DMP.zip)

**Comment by SlimCognito91** [comment]
Old 3DSXL
Firmware: 11.8.0-41U
CFW - Luma 9.1-89cc6ed
Anemone3DS- 2.1.0-b

I have about 46 themes and 8 splashes. Crash is consistent when scrolling themes but not splashes just as RinMaru mentioned. 
[SlimOld3DSLumaDump1-1-19.zip](https://github.com/astronautlevel2/Anemone3DS/files/2719554/SlimOld3DSLumaDump1-1-19.zip)

**Comment by SlimCognito91** [comment]
I wanted to make a separate comment for another crash found during my last post. Here is another dump of a crash happening when using the START button to exit the application. 
I hope this helps and that I'm not making issues with the extra comment.

Same hardware, firmware, and CFW, and latest version of Anemone3DS as above.
Thank you for your contribution to the homebrew scene.

[START to exit crash dump.zip](https://github.com/astronautlevel2/Anemone3DS/files/2719562/START.to.exit.crash.dump.zip)

**Comment by 5kyl4rk** [comment]
I was having this same problem, I could't scroll past icon 8, but then I accidentally press the "filter"(?) icon (the one next to the download button) and surprisingly it worked, I could scroll down to the bottom without any problems (so far).

**Comment by RinMaru** [comment]
so i guess this project is dead?

**Comment by Helloman892** [comment]
The project isn't dead so much as we're all real people.

Please refrain from commenting on issues unless you have something to contribute, even if it's your own issue.

**Comment by astronautlevel2** [comment]
The project is still being worked on.

For now you should use a previous version of the software (v2.0.1) instead of the beta.

**Comment by astronautlevel2** [comment]
Closing as various 2.1.0 commits should have fixed this
