### ISSUE TITLE
Shuffle splashes

### ISSUE THREAD

**Issue by GamingWessel** [astronautlevel2/Anemone3DS#197]
Hey, you said in #34 (which was posted in 2017) that you were planning on adding support for shuffling splashes, too. 

Any updates / ETA on this?

Thanks,
Wessel

**Comment by Helloman892** [comment]
Shuffling splashses is non-trivial, and at current (and for the past couple months) none of us really have the time for adding such features. It'll be here eventually, but don't expect it even Soon:tm:.

**Comment by GamingWessel** [comment]
Ok, thank you
