### ISSUE TITLE
Sleep mode battery drain

### ISSUE THREAD

**Issue by willis936** [astronautlevel2/Anemone3DS#199]
When using shuffled themes the battery drain is very high in sleep mode (no software running, clamshell closed, less than 8 hours).

**Comment by astronautlevel2** [comment]
This is a problem with the 3DS homemenu itself, not Anemone.

**Comment by willis936** [comment]
I'm not sure how you came to that conclucion.  When I switched from anemone to a first party theme the battery drain issue went away.

**Comment by astronautlevel2** [comment]
Anemone3DS installs themes in the exact same way that the 3DS home menu does. The shuffle theme code is entirely Nintendo's - all Anemone does is install the files.
