### ISSUE TITLE
Anemone loads default theme

### ISSUE THREAD

**Issue by Draco-Est-Invicte** [astronautlevel2/Anemone3DS#201]
I recently got anemone on my old 3ds with the latest cfw. I then scanned the qr code of the custom themes I wanted to install. The themes are downloaded and then i install with bgm. It says that the theme is installed, but when I reboot my 3ds, the default theme is loaded and the custom theme isn't installed

**Comment by JustBuddy** [comment]
Try to apply any official theme from the stock theme app first. (can be one of the preinstalled colored ones.)
Then apply your downloaded theme from Anemone.
