### ISSUE TITLE
Splashes screens doesn't shows

### ISSUE THREAD

**Issue by joshcast96** [astronautlevel2/Anemone3DS#202]
Im trying to install a splash screen with anemone, the thing is that when i install the splash and reset the console it doesn't appears, i tried to install it via QR code, and made sure that the installed splash was in the luma folder, i erased the splash, and tried to unzip it manually into the luma folder, (the luma configuration its set to "before"), also tried to re install the anemone, and with differents splashes, nothing seems to work.

**Comment by HeraldOD** [comment]
Have you enabled the splash screen in Luma settings (hold select during boot)?

**Comment by joshcast96** [comment]
Yes, as i said, luma config its set to "before"

**Comment by joshcast96** [comment]
Does anyone has an idea of how can i fix this?

**Comment by Helloman892** [comment]
If you manually placed the splash into the folder, and it *still* didn't work, this isn't a problem with Anemone3DS.

If you still can't find a solution, I suggest making an issue on the Luma3DS repository (if you haven't already).
