### ISSUE TITLE
Cannot Scan QR Codes from Other Sites

### ISSUE THREAD

**Issue by Ratismal** [astronautlevel2/Anemone3DS#204]
Hello,

I'll preface this issue by saying that I'm using v2.1.0-b.

### Preamble

I was developing a theme when I got a bit tired of my workflow; exit anenome, open ftp, transfer file, exit ftp, open anenome, test. I thought I'd streamline the process.

So, I quickly spun up a local webserver to serve my theme from, as well as a batch script to zip my files and move to my server. I'm now able to access my theme on any local device from `http://192.168.0.22:8080/<filename.zip>`. I generated a QR code from this, and joyfully scanned it.

Now here's where the problems start. First of all, anenome expects an ID at the end of the filename `name (id).zip`. There's apparently no checks for this, and the download immediately fails. Now, the fun part is that trying to use the QR scanner after this causes the entire system to crash (sometimes it even crashes without trying to use the QR scanner again!).

![mmm tasty!](https://cats.are-pretty.sexy/yEX6Pc2.jpg)

All QR functionality then ceases to function until you completely reinstall the app.

So, I appended a fake ID `(1234)` to my file, but alas it still fails to download, but without crashing. Though, if I try enough times, the program freezes and I have to do a hard reset.

#### Note

I'm pretty sure the whole needs-an-id is a new thing imposed by the beta. Themes downloaded on the beta are renamed `<id>.zip`, whereas the latest actual release retains the full name of the zip. However, my theme still fails to download on both.

### Question

In #75 it states that QR codes from other sites should work, as long as it points to a valid theme.

I'm fairly certain my theme is valid. as I'm able to install it fine when transferring via ftp.

I know for sure my local webserver is accessible, because... well, I can access it.
![wow! im really here!](https://everyone.needs-to-s.top/3nB5LEa.bmp)

I've uploaded my theme in case I'm doing something wrong with the file structure or something: [p52 (1234).zip](https://github.com/astronautlevel2/Anemone3DS/files/3194452/p52.1234.zip)

QR code for ^ (will do the crashydoodle for v1.2.0-b though because github renamed it)
![image](https://user-images.githubusercontent.com/1059362/57974481-fd574400-7975-11e9-93f1-092adbba3add.png)

Any help would be greatly appreciated. If additional information is required, feel free to ask!

Thank you ^w^

**Comment by astronautlevel2** [comment]
The second issue was caused by a double free when the download was aborted and has been fixed in 2c2c7f4b33335ee6822c658f7ef8c8e969393a98.

The first issue is caused by differences in how the content disposition header is presented - ThemePlaza sends it in the format of `filename="some theme (1234).zip"` whereas discord and some other sites seem to send it as `filename=some thing (1234).zip` (notice the lack of quotes). The software assumes the quotes are there and crashes if it attempts to download from a source without them - this isn't too hard a fix and I'll get it done later today.

**Comment by Helloman892** [comment]
Fixed by no longer assuming that a delimiter for the filename exists.
It's likely more efficient to check specifically for a quote, but I'll leave that for later.
I'll open a new issue detailing an issue related to this shortly.
