### ISSUE TITLE
Scroll crash, theme browser loading missing pages crash and previewing themes that aren't installed crash.

### ISSUE THREAD

**Issue by zxUltra** [astronautlevel2/Anemone3DS#206]
Scroll crash:
If you search something like "nintendo" or any keyword in Theme Plaza Browser that has an incomplete page (example: if it has 2 pages but the second page isn't full), if you select a theme on one page, and then scroll to the next page, the theme you selected will carry over the selection to the next page. Then this will appear:
![20190530_202136 1](https://user-images.githubusercontent.com/51272139/58752326-a5602780-84b5-11e9-8fa3-cc2c2563538c.jpg)
If you preview it, it causes a kernel panic (oof). I didn't try to download it since i don't want to risk it corrupting my SD Card or the entire system.

Theme Browser loading missing/corrupted pages crash:
Yeah, um, it sort of speaks for itself. If you got to the end of the search results, you might expect to not let you go further, but here, it, for some reason, does. If you do go further however, it loads voids and generates garbage data that crashes the system. And it gives the Fault status to "Data abort"

Previewing themes that aren't installed crash:
This one is random at best. You have no idea when it occurs. When it occurs, it occurs. It is so random it even messes up the boot up sequence. (Is it a normal thing that happens during more severe crashes? Because for the other crashes, it boots normally without interrupts.)
It only messes up the boot up process if you press the power button and not any of the other buttons (excluding A used for dumping the crash log):
![20190530_191421 1](https://user-images.githubusercontent.com/51272139/58752477-186a9d80-84b8-11e9-8776-76e79b8e5cbe.jpg)
![20190530_192122 1](https://user-images.githubusercontent.com/51272139/58752532-fe7d8a80-84b8-11e9-9de9-d781606c8eaf.jpg)

Version 2.0.1

**Comment by ChampionLeake** [comment]
I'm getting the same issue with scrolling

**Comment by Oreo639** [comment]
> I'm getting the same issue with scrolling
Do you mean this:
https://github.com/astronautlevel2/Anemone3DS/issues/196

**Comment by ChampionLeake** [comment]
Just scrolling once or twice just crashes the application

**Comment by Helloman892** [comment]
We're currently going over a rewrite of the application, which happens to fix this and many other bugs. It might still take a few weeks, because we're all moderately busy with our real lives, so please bear with us!

**Comment by Helloman892** [comment]
RE: that rewrite, it still hasn't happened - however, I also can't replicate this. Can anybody else?

**Comment by astronautlevel2** [comment]
This was likely fixed already as part of a previous commit, though I'm not sure which one - closing.
