### ISSUE TITLE
Adding BGM themes to the default nintendo shuffle?

### ISSUE THREAD

**Issue by GiacomoLaw** [astronautlevel2/Anemone3DS#207]
I have a few themes from the theme shop. How can I integrate them themes from Theme Plaza?

Thanks!

**Comment by Helloman892** [comment]
Not using Anemone, you can't - see [Howling Theme Tool](https://gbatemp.net/threads/release-howling-theme-tool-create-your-own-cia-theme-packages-with-custom-and-official-themes.401081/).

**Comment by GiacomoLaw** [comment]
Will do, thanks
