### ISSUE TITLE
Theme installed properly, but not appearing after Reboot

### ISSUE THREAD

**Issue by ToastSama** [astronautlevel2/Anemone3DS#210]
Hello, I have a New Nintendo 3DS XL and I recently installed Anemone3DS v2.0.1. The Splash screen is functioning fine. However, when I apply a theme it only works when I press START and then hit the HOME button.
![20190807_221900](https://user-images.githubusercontent.com/53890098/62677136-17476800-b962-11e9-9320-41d1b45ce8b5.jpg)
![20190807_221936](https://user-images.githubusercontent.com/53890098/62677151-2201fd00-b962-11e9-8315-9ecc9264034b.jpg)
After rebooting, the 3DS the home screen defaults to "Do not use a theme."
![20190807_222027](https://user-images.githubusercontent.com/53890098/62677160-2a5a3800-b962-11e9-9c15-3d482bd76e58.jpg)
Any advice to fixing this is issue is greatly appreciated.

**Comment by staticanime** [comment]
I have the same issue.

I modded my new 3DS XL last week using the 3ds.hacks guide and an old 4GB Lexar SD-HC card I had lying around, and themes worked fine on it.
I then copied my SD data to a 128GB SanDisk Ultra SD-XC Class II card to have more space. Again, themes worked fine, but I found the write speeds installing games unbearably slow.
So, lastly, I moved to a 256GB SanDisk Ultra SD-XC Class 10 U1/A1, and now themes do not work after reboot.

Going back to the 128GB, themes work fine. Going back to the 4GB, themes work fine, it's just this 256GB card that has this issue.

For reference, all cards were formatted FAT32, with a 32kb allocation size, using Rufus (https://rufus.ie/)

New to the 3DS scene, but happy to do any further testing to try see what the issue is?

**Comment by staticanime** [comment]
> I have the same issue.
> 
> I modded my new 3DS XL last week using the 3ds.hacks guide and an old 4GB Lexar SD-HC card I had lying around, and themes worked fine on it.
> I then copied my SD data to a 128GB SanDisk Ultra SD-XC Class II card to have more space. Again, themes worked fine, but I found the write speeds installing games unbearably slow.
> So, lastly, I moved to a 256GB SanDisk Ultra SD-XC Class 10 U1/A1, and now themes do not work after reboot.
> 
> Going back to the 128GB, themes work fine. Going back to the 4GB, themes work fine, it's just this 256GB card that has this issue.
> 
> For reference, all cards were formatted FAT32, with a 32kb allocation size, using Rufus (https://rufus.ie/)
> 
> New to the 3DS scene, but happy to do any further testing to try see what the issue is?

I don't know why, but, I managed to resolve the issue by turning on Enable game patching in Luma3DS settings (select on boot), which i turned on for an unrelated reason. Themes are now fully working for me. Strange that this is required for the 256GB SD card, and not for the smaller one, but I'll take the little victory!

![IMG_20190822_211137](https://user-images.githubusercontent.com/394875/63546394-a4252080-c521-11e9-9ead-a29728c21597.jpg)

**Comment by ToastSama** [comment]
Thank you so much for persisting and resolving this issue. I hope others struggling with the same issue we had can benefit from your victory.

As a side note, the Micro SD card I used was a SanDisk Ultra 128GB SD-XC UHS-1 Class 10. Formatted to FAT32 with 32kb allocation size using the free version of the program MiniTool Partition Wizard.

**Comment by dustinKnight** [comment]
> 
> 
> > I have the same issue.
> > I modded my new 3DS XL last week using the 3ds.hacks guide and an old 4GB Lexar SD-HC card I had lying around, and themes worked fine on it.
> > I then copied my SD data to a 128GB SanDisk Ultra SD-XC Class II card to have more space. Again, themes worked fine, but I found the write speeds installing games unbearably slow.
> > So, lastly, I moved to a 256GB SanDisk Ultra SD-XC Class 10 U1/A1, and now themes do not work after reboot.
> > Going back to the 128GB, themes work fine. Going back to the 4GB, themes work fine, it's just this 256GB card that has this issue.
> > For reference, all cards were formatted FAT32, with a 32kb allocation size, using Rufus (https://rufus.ie/)
> > New to the 3DS scene, but happy to do any further testing to try see what the issue is?
> 
> I don't know why, but, I managed to resolve the issue by turning on Enable game patching in Luma3DS settings (select on boot), which i turned on for an unrelated reason. Themes are now fully working for me. Strange that this is required for the 256GB SD card, and not for the smaller one, but I'll take the little victory!
> 
> ![IMG_20190822_211137](https://user-images.githubusercontent.com/394875/63546394-a4252080-c521-11e9-9ead-a29728c21597.jpg)

I was also using a 256 micro sd card that was formatted in the same way and had the same issue. This solution fixed my problem also. I was just commenting for confirmation.

**Comment by widardd** [comment]
Same, also 256GB card, enabling gamepatching fixes it. Thank you!

**Comment by eisnerguy1** [comment]
Same here as well. Thank you!!

**Comment by ottawagamerz** [comment]
thank u so very much it worked :)

**Comment by Wamy-Dev** [comment]
> > I have the same issue.
> > I modded my new 3DS XL last week using the 3ds.hacks guide and an old 4GB Lexar SD-HC card I had lying around, and themes worked fine on it.
> > I then copied my SD data to a 128GB SanDisk Ultra SD-XC Class II card to have more space. Again, themes worked fine, but I found the write speeds installing games unbearably slow.
> > So, lastly, I moved to a 256GB SanDisk Ultra SD-XC Class 10 U1/A1, and now themes do not work after reboot.
> > Going back to the 128GB, themes work fine. Going back to the 4GB, themes work fine, it's just this 256GB card that has this issue.
> > For reference, all cards were formatted FAT32, with a 32kb allocation size, using Rufus (https://rufus.ie/)
> > New to the 3DS scene, but happy to do any further testing to try see what the issue is?
> 
> I don't know why, but, I managed to resolve the issue by turning on Enable game patching in Luma3DS settings (select on boot), which i turned on for an unrelated reason. Themes are now fully working for me. Strange that this is required for the 256GB SD card, and not for the smaller one, but I'll take the little victory!
> 
> ![IMG_20190822_211137](https://user-images.githubusercontent.com/394875/63546394-a4252080-c521-11e9-9ead-a29728c21597.jpg)

This worked perfectly for me! Thank you!

**Comment by Apostleerebus** [comment]
This is a beautiful fix

**Comment by FireCubX** [comment]
> > I have the same issue.
> > I modded my new 3DS XL last week using the 3ds.hacks guide and an old 4GB Lexar SD-HC card I had lying around, and themes worked fine on it.
> > I then copied my SD data to a 128GB SanDisk Ultra SD-XC Class II card to have more space. Again, themes worked fine, but I found the write speeds installing games unbearably slow.
> > So, lastly, I moved to a 256GB SanDisk Ultra SD-XC Class 10 U1/A1, and now themes do not work after reboot.
> > Going back to the 128GB, themes work fine. Going back to the 4GB, themes work fine, it's just this 256GB card that has this issue.
> > For reference, all cards were formatted FAT32, with a 32kb allocation size, using Rufus (https://rufus.ie/)
> > New to the 3DS scene, but happy to do any further testing to try see what the issue is?
> 
> I don't know why, but, I managed to resolve the issue by turning on Enable game patching in Luma3DS settings (select on boot), which i turned on for an unrelated reason. Themes are now fully working for me. Strange that this is required for the 256GB SD card, and not for the smaller one, but I'll take the little victory!
> 
> ![IMG_20190822_211137](https://user-images.githubusercontent.com/394875/63546394-a4252080-c521-11e9-9ead-a29728c21597.jpg)

You are the best! Mvp! Made a github just to reply to this

**Comment by Error404Danny** [comment]
May be late to the party, But I can also comfirm that it did work as well on my end. I tried it on 2 3ds systems, one old 3ds xl and one new 3ds xl and it worked on both. Thanks again. Will put this link as a reference on my reddit post in the case someone elsem comes across this issue.

**Comment by blakehuntington** [comment]
Same here @Error404Danny 

I can confirm that selecting "Enable game patching" fixed it!

**Comment by pikaman1** [comment]
for me this did not work I have a 64 gigabyte micro sd card in my 3ds I have tried multiple things when i saw this for me it did not work does anyone know of any other ways only my splash screen shows up all i did was update luma 3ds to the latest release

**Comment by SplitCoreGaming** [comment]
Posting as of 29/05/2023 

> > I have the same issue.
> > I modded my new 3DS XL last week using the 3ds.hacks guide and an old 4GB Lexar SD-HC card I had lying around, and themes worked fine on it.
> > I then copied my SD data to a 128GB SanDisk Ultra SD-XC Class II card to have more space. Again, themes worked fine, but I found the write speeds installing games unbearably slow.
> > So, lastly, I moved to a 256GB SanDisk Ultra SD-XC Class 10 U1/A1, and now themes do not work after reboot.
> > Going back to the 128GB, themes work fine. Going back to the 4GB, themes work fine, it's just this 256GB card that has this issue.
> > For reference, all cards were formatted FAT32, with a 32kb allocation size, using Rufus (https://rufus.ie/)
> > New to the 3DS scene, but happy to do any further testing to try see what the issue is?
> 
> I don't know why, but, I managed to resolve the issue by turning on Enable game patching in Luma3DS settings (select on boot), which i turned on for an unrelated reason. Themes are now fully working for me. Strange that this is required for the 256GB SD card, and not for the smaller one, but I'll take the little victory!
> 
> ![IMG_20190822_211137](https://user-images.githubusercontent.com/394875/63546394-a4252080-c521-11e9-9ead-a29728c21597.jpg)

Can confirm as of 29/05/2023 this helped on latest CFW's and New 3DS XL. Many thanks.

**Comment by lobro3** [comment]
It worked after I upgraded to a 256 gb micro sd card thank you!

**Comment by casttrocollar** [comment]
I also dragged my customized theme, but it didnt install. the Checked logo didnt appeared. I just dragged "bgm.bcstm", it has the loop thing there. When i pressed 'START", it just proceeds to the HOME Menu

**Comment by Error404Danny** [comment]
I’m not really sure how customized themes work. Bc usually it’s a .cia file on the Fbi app that downloads it to the Home Screen and then you install it on your 3ds and then use Anemone to set it up. I know some people make it a QR code and install it that way. Not sure how to help besides that.

**Comment by TurtleFanCoder** [comment]
Update for y'all: It's not enabling the option that makes the themes work, for me it was already enabled and the themes weren't working. When I decided to _disable_ the option, however, the themes worked.
