### ISSUE TITLE
[QUESTION] Why there is an elf version of this ?

### ISSUE THREAD

**Issue by LuuNyX** [astronautlevel2/Anemone3DS#211]
Hi,
All is on the title...

**Comment by Oreo639** [comment]
I assume debugging.
Loading the elf in $DEVKITARM/bin/arm-none-eabi before connecting the application to it allows for extra information to be given about where in the code a crash occurs along with other stuff.
Correct me if I am wrong.

**Comment by LuuNyX** [comment]
'kay, but why this file is send as Release ? If it's just for debug. (Thx for your fast reply anyway)

**Comment by LiquidFenrir** [comment]
There's no guarantee that when recompiling the release to get the elf and debug that you'll get the exact same one.
But you need it to be the same bit by bit for debugging tools to work, so it gets sent in case the devs delete it from their pc, so they can just download it again and debug the release.
Hope that helped

**Comment by LuuNyX** [comment]
Okay, thanks for all ! You've helped me !
