### ISSUE TITLE
Random Splash Screen on Luma

### ISSUE THREAD

**Issue by jvcastel** [astronautlevel2/Anemone3DS#212]
Now that Anemone handles splash screens, it would be interesting to add a randomizer for the splash screen. The idea would be as follows: after Luma loads, then run a module that  replaces the splash.bin and the splashbottom.bin file from one to the splash files located on the splashes folder on the SD. This way every time the 3DS is turned on a different splash screen is shown. 
Would be interesting to try out.
Thanks!
jvcastel

**Comment by Oreo639** [comment]
Luma does not currently allow loading custom sysmodules (just replacing sysmodules).

Besides, this would probably be better to implement in luma instead of using some hacky workaround.
Just my two cents though.

**Comment by Helloman892** [comment]
Cleaning up issues - Oreo is entirely right, Luma itself doesn't allow our userland app to do this.
