### ISSUE TITLE
No BGM flag in theme body overrides BGM install

### ISSUE THREAD

**Issue by DiegoBranco** [astronautlevel2/Anemone3DS#216]
Using Anemone 2.1.0-b on an O3dsXL: 

If i install a skin that has no Music with either NoBGM Install or regular install, then install a skin that has music with a BGM Only install, it wont play the song. 

It will only play the default sfx as if the second install never happened.

**Comment by astronautlevel2** [comment]
Theme bodies themselves (the body_lz file) have a flag that indicates whether they have BGM or not, and if that flag is set to no BGM, the 3DS home menu won't try to play music, even if a BGM is later copied onto the NAND. I think this can be worked around, but I'm not sure when I'll get around looking into it.

**Comment by astronautlevel2** [comment]
Some more thoughts on the issue:

1. The decompressed body_lz.bin's 5th byte is responsible for controlling whether or not BGM is enabled
2. The body_lz.bin file is compressed using Nintendo's LZ11 algorithm
3. Although there are C programs to decompress LZ11 files, I can't find any to re-compress them

If there was a C program to compress LZ11 files this would be a fairly trivial feature to implement (just open the theme file, change the byte, and re-compress it), but given that I can't find any it means I'd need to reimplement a python or similar LZ11 compression program in C, which could take a bit more time. I'll get this done at some point, but probably the soonest I'll be able to take a real crack at it is this weekend.

**Comment by astronautlevel2** [comment]
6bafa6a22e9bf7f37aeecdfcab81b8438cd9b359 is the first part of this done, I'm going to work on adding the compression code tomorrow. Should hopefully have it done by Wednesday at the latest.

**Comment by astronautlevel2** [comment]
Hi @DiegoBranco,

I think 36e8104dbb004b27dbe42a08327e68cee608ba1b should fix your issue. I've attached a build which you can try out.

Let me know if it still doesn't work. Thanks!

https://cdn.discordapp.com/attachments/352824412782854157/722583782246318120/Anemone3DS.cia

![canvas](https://user-images.githubusercontent.com/7305572/84835754-46a71680-b002-11ea-9998-9050102dc810.png)

**Comment by DiegoBranco** [comment]
You beautiful genius! it works exactly like i wanted! thanks man.

**Comment by DiegoBranco** [comment]
Actually, after further testing, this breaks skins that do have bgm. 

Now to use those i have to install them twice (no-bgm install, then bgm-only install)

**Comment by astronautlevel2** [comment]
Yep, I had a minor oversight. Can you try this build?
![canvas](https://user-images.githubusercontent.com/7305572/84853099-64897100-b02c-11ea-895a-19376fffdcf5.png)

**Comment by DiegoBranco** [comment]
This one does work properly. Thanks!
