### ISSUE TITLE
Memory Leak in load_preview_from_buffer

### ISSUE THREAD

**Issue by pyroticinsanity** [astronautlevel2/Anemone3DS#217]
I was using this code as an example for loading PNGs and noticed that it is leaking memory every time you load an image. My application ran out of memory after loading ~ 10 1024x1024 PNG files.

https://github.com/astronautlevel2/Anemone3DS/blob/193feedf25ca7e0c4b99fe1552d99ad552cb9200/source/loading.c#L506
`
    png_bytep * row_pointers = malloc(sizeof(png_bytep) * height);
    for(int y = 0; y < height; y++) {
        row_pointers[y] = (png_byte*)malloc(png_get_rowbytes(png,info));
    }
`

These mallocs need to be freed prior to exiting the function.

**Comment by Helloman892** [comment]
Thanks for spotting this.

**Comment by pyroticinsanity** [comment]
You're welcome! Thanks for writing 3DS PNG code that was easy to use.
