### ISSUE TITLE
No proper handling when the filename isn't specified but the target is a file (http_get)

### ISSUE THREAD

**Issue by Helloman892** [astronautlevel2/Anemone3DS#220]
We don't correctly* handle the case where the `filename` parameter isn't ~~actually~~ filled. See [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition).

**Comment by astronautlevel2** [comment]
I'm not entirely familiar w/ content disposition, in the case filename isn't provided, is there any other way to get the name of the file?

**Comment by Helloman892** [comment]
Not sure, but it'd be documented there. I'll have a look in a bit.

**Comment by Helloman892** [comment]
@astronautlevel2: The way to handle this would probably be to fire up the swkbd and ask for a name to save as if none is given in the header.

**Comment by Helloman892** [comment]
Also, we currently handle it [here](https://github.com/astronautlevel2/Anemone3DS/blob/master/source/remote.c#L814-L822); we should probably handle this differently than just assuming that the target isn't valid at all. I'll look into this more when we come around to the rewrite.

**Comment by Helloman892** [comment]
#240 makes an attempt at fixing this, but ultimately doesn't yet. I'll finish that up promptly.
