### ISSUE TITLE
Problems Manually Installing Themes

### ISSUE THREAD

**Issue by platinumrad** [astronautlevel2/Anemone3DS#221]
My shoulder buttons do not work. I have created a folder called Themes in root and placed the theme files (zip folder) in the folder. However, they don't seem to be recognized by Anemone at all.

**Comment by Helloman892** [comment]
Do those ZIPs contain an `info.smdh`, as in any theme Theme Plaza hosts?

**Comment by astronautlevel2** [comment]
Can you zip the themes folder and upload it here? Thanks.

**Comment by platinumrad** [comment]
I've managed to solve the problems after all. Turns out I needed to create 3DS theme data from the system.
