### ISSUE TITLE
Theme Preview RGB bug  

### ISSUE THREAD

**Issue by Syko7956** [astronautlevel2/Anemone3DS#227]
![2020-07-03_11-41-30 471_top](https://user-images.githubusercontent.com/16283463/86483690-92f09700-bd22-11ea-82b5-55b7dd9d7645.png)
Some do this, some don't
Versions before the revival doesn't have this issue on any of them

**Comment by Syko7956** [comment]
It's fine when installed though. It's just the preview

**Comment by Helloman892** [comment]
This is almost certainly to do with PNG decoding, and is an issue I've had reported to me before. I'll sit down and look at this when I get a moment.

**Comment by Syko7956** [comment]
Thank you!

**Comment by Syko7956** [comment]
I can confirm this is fixed on my end. Good work!
