### ISSUE TITLE
Anemone not booting (Black screen)

### ISSUE THREAD

**Issue by Crissmore** [astronautlevel2/Anemone3DS#233]
I used to instal custom themes with anemone a few years ago but my 3ds stoped showing games and everything cfw related on home menu. 
A few months ago i solved this problem changing my sd and updating luma and hblauncher.
Now everytime i try to open Anemone or any other themes cfw i get a black screen and nothing else, this happens with the 3dsx and the cia version, what should i do? I have already deleted Home Menu extdata on Nintendo 3ds/ folder but it does not solve the problem.

3ds version 11.13.0-45U
Luma version 10.2
HBlauncher version 2.2.0

**Comment by Helloman892** [comment]
If you're having trouble with other applications, this isn't anything we can fix.

Feel free to reopen the issue if it's only Anemone3DS that doesn't work, but for now, closing as invalid.
