### ISSUE TITLE
Audio works in Usagi Theme Editor preview and Anemone3DS preview, but theme won't install

### ISSUE THREAD

**Issue by meowmeoe** [astronautlevel2/Anemone3DS#234]
My audio file that I made in Looping Audio Converter loads in Usagi Theme Editor and plays fine.  Same in the Anemone theme preview on my 2DS.  For some reason, though, I can't install it unless I do "No BGM".  When I try, it won't put a check mark on my theme or load my theme at all in the Home Menu.

**Comment by vxcreation** [comment]
Same here.

**Comment by Helloman892** [comment]
@vxcreation, this is unrelated.
@meowmeoe, this is an issue with your BGM file - the preview we play is an `ogg` file, not a `bcstm` file. Correct me if I'm wrong, but your `bgm.bcstm` file is larger than 3.3MiB (3371008 bytes exactly), and this will (in the current release of Anemone3DS) cause the installation to fail silently.

Feel free to reopen this issue if you still have the problem after reducing your `bgm.bcstm`'s filesize to below 3.3MiB.
