### ISSUE TITLE
Very small typo on the keyboard selections

### ISSUE THREAD

**Issue by itstoast27** [astronautlevel2/Anemone3DS#236]
When opening up the menu for searching things online, _"Cancel"_ is mispelt as _"Cance"_. I know this is stupid and small, and probably useless, but I guess somebody should point it out so that it can be fixed in the next update.

**Comment by Helloman892** [comment]
https://github.com/astronautlevel2/Anemone3DS/blob/master/source/remote.c#L387

In other words, right you are. Thanks for pointing this out, I'll fix it promptly.
