### ISSUE TITLE
Qr scanner seems to crash new 3ds

### ISSUE THREAD

**Issue by linusrg1** [astronautlevel2/Anemone3DS#238]

**Comment by Helloman892** [comment]
This isn't a bug report. Closed as invalid.

**Comment by linusrg1** [comment]
it is though. The bug is the qr code scanner crashes the app.

**Comment by Helloman892** [comment]
Ok, so let's say it is a bug report. What do you want us to do about it? You haven't given us any information, you haven't shown us what 'crash' it causes, nor have you told us whether it can be replicated and how to do so.

We are all quite busy right now with things other than this issue tracker, and hence we don't really have time for bug reports that aren't helpful. Again, feel free to reopen this issue if you can provide us more information.

**Comment by linusrg1** [comment]
cause I thought that would be self explanatory. It happens when you click on the qr download button. Something u should know about as you helped design the app im assuming. And then you have to force restart your 3ds.

**Comment by Helloman892** [comment]
I had a quick look, and we already have a mature issue about this problem (#189).

In future, when making bug reports, please give us as much information as possible - your 3DS model and region, your system software version, which custom firmware (e.g. Luma3DS, ReiNand) you are using and on which version, and the version of Anemone3DS that the problem occurs in. It's also worth taking a look through the open issues to ensure that the problem you're experiencing hasn't already been reported.
