### ISSUE TITLE
Shuffled Themes Playing Over Another

### ISSUE THREAD

**Issue by atyfaz** [astronautlevel2/Anemone3DS#241]
I've been trying to get some themes working and I made some BCSTM files using Looping Audio Converter 1.3.3 (with the BrawlLib plugin) and I am running into an issue where whenever one of my themes play, if a theme that wasn't mine played before it, it will play a sped up or slowed down beginning loop of the other theme  overtop of mine at the same time. My theme will play and loop normally but I will hear the first 5 seconds of another theme over and over at sped up or slowed down pace.

All my themes work fine if they're the first theme to run. To give an example to better explain: If I boot up my 3DS and the first theme is Paper Mario TTYD (not mine), it plays normally. Then if I make the theme shuffle to something by closing my 3DS and opening it or going into notes, and one of my themes plays, it will play my themes music, but the first few seconds of TTYD will play at the same time. If I shuffle and get another one of my themes, it has the same problem of playing TTYD but likely at a different speed. If I shuffle and get a theme not made by me, they will always work perfectly and have no audio overlapping.

I don't know what I'm doing wrong and I've scowered the internet and can't find a single account of someone experiencing similar. I've tried just about every option in Looping Audio Converter. I've tried starting with wavs, mp3s, and the result never changes.

I'm not sure this is an issue with Anemone3DS, Looping Audio Converter, or it's just me doing something wrong, but I literally can't find any info via Google to fix this no matter how many different terms I try to search. If anyone could please point me in the right direction as to why I'm having trouble with this I would be super grateful. Thank you.

**Comment by astronautlevel2** [comment]
This is pretty weird. I can't imagine what would be causing this given that the theme BGMs are contained in separate files. Can you post one of your themes here so I can take a closer look at it?

**Comment by atyfaz** [comment]
> 
> 
> This is pretty weird. I can't imagine what would be causing this given that the theme BGMs are contained in separate files. Can you post one of your themes here so I can take a closer look at it?

Here's a theme I made about Kid Icarus Uprising. I did start with another users theme as a base but changed pretty much every single thing, but I think I still credited them in the description despite having changed every asset and color they used anyway.
[https://drive.google.com/file/d/17jHyjL4B9uzlvgzU8xgjp0WofCP7wnzc/view?usp=sharing](url)

I have made 4 other themes that all face the same issue when shuffle installed. The 5 themes that aren't mine however always work perfectly and I'm not sure what makes theirs different than mine.

**Comment by astronautlevel2** [comment]
Let me take a look at it. You may also want to head over to the [ThemePlaza discord](https://discord.gg/xHq4QZnD) and describe your process in the theming-help channel and see if they notice anything wrong.

**Comment by astronautlevel2** [comment]
Let me take a look at it. You may also want to head over to the [ThemePlaza discord](https://discord.gg/xHq4QZnD) and describe your process in the theming-help channel and see if they notice anything wrong.

**Comment by astronautlevel2** [comment]
Actually, the issue may be pretty simple; your bcstm output is mono whereas I believe most themes use stereo. Give switching it to stereo a try?

**Comment by atyfaz** [comment]
> 
> 
> Actually, the issue may be pretty simple; your bcstm output is mono whereas I believe most themes use stereo. Give switching it to stereo a try?

I will try this and let you know. The guide I read said to use mono because it saves space to keep the bcstms under 3.3mb. I'll do a test and set one to stereo and see if works. Might have to redo all the bcstms if thats the case because they might exceed 3.3mb if they're put back to stereo. Thank you so much for helping me on this.

**Comment by astronautlevel2** [comment]
Mono does reduce the size but it causes a lot of potential issues as well. Generally we recommend avoiding it for exactly that reason. Let me know if it fixes the issue and if it does feel free to close the issue.

**Comment by atyfaz** [comment]
> 
> 
> Mono does reduce the size but it causes a lot of potential issues as well. Generally we recommend avoiding it for exactly that reason. Let me know if it fixes the issue and if it does feel free to close the issue.

This was exactly the issue. I converted the other themes to mono (since I didn't really wanna shorten my themes) and now they all work together. I have a 2DS so it only has mono speakers anyway. I'll make sure to always have shuffle themes all be mono or stereo from now on. Thank you a bunch for all the help and I hope you have a wonderful holidays and new year.
