### ISSUE TITLE
Bug in ThemePlaza

### ISSUE THREAD

**Issue by Lenorr** [astronautlevel2/Anemone3DS#243]
In the ThemePlaza, you can hover over empty fields by scrolling horizontally (Vertically wont work). You can "Install" these, but it just crashes your 3ds.
![IMG_20210102_034215](https://user-images.githubusercontent.com/76857356/103449705-871f6680-4cac-11eb-8145-f64d220e3231.jpg)

**Comment by Helloman892** [comment]
@astronautlevel2 I thought you fixed this?

**Comment by Helloman892** [comment]
That said, I can replicate this on latest. I'll look into it more tomorrow, I guess.

**Comment by astronautlevel2** [comment]
Fixed a similar but unrelated bug (see #206) which involved selecting a valid theme, then switching pages, resulting in the cursor landing on a non-existent theme. I'll take a look at this now.

**Comment by astronautlevel2** [comment]
Fixed in e4e0118c1a5781279e22c55e767706f23c6df7d0
