### ISSUE TITLE
Installing any BGM to Official theme causes it to crash

### ISSUE THREAD

**Issue by CloverNoir** [astronautlevel2/Anemone3DS#244]
More specifically, this happens ONLY with the Umbreon and Espeon theme, none of the other themes I've tried seem to have this issue. 
I've tried installing different bgm themes, i've also tried directly replacing the bcstm and ogg, but all of these lead to a crash that forces me to delete the extdata folder (more specifically, the 000002cd folder). 
The theme works just fine if I don't change its background music. I tried installing the most recent version of Anemone too, but it didn't fix the issue. 
I don't know what's up with this theme, the 3ds theme editor seems to detect it just fine, even with the changed bgm. 
![20210123_225710](https://user-images.githubusercontent.com/77909002/105621598-e44f9900-5dce-11eb-8d17-6cdd63679bdd.jpg)

**Comment by CloverNoir** [comment]
Just fixed it, had to rebuild the theme using 3ds theme editor. Extracted the files from the original theme and just imported them to a new theme project, there i just followed the usual process of making a custom theme. No idea why this was happening in the first place, but this fixed it, so that's that! Surely this wasn't really Anemone's fault and most likely was just the theme itself being stubborn, so im closing this now. Sorry for the unnecessary issue.

**Comment by Helloman892** [comment]
@CloverNoir: No problem, glad you could get it fixed. I remember looking at my phone last night and going 'this isn't us', but clearly you worked that out yourself!
