### ISSUE TITLE
Feature Request: Set theme by time (Day/Night)

### ISSUE THREAD

**Issue by rorotheworld** [astronautlevel2/Anemone3DS#245]
Not sure if this would be possible, but I thought scheduled themes could be a neat feature. For example one "day theme" and one "night theme". Being able to arbitrarily assign themes to certain time frames would be even better.

Either way thank you for your work! This is a fantastic piece of homebrew.

**Comment by Helloman892** [comment]
This isn't possible, as the 3DS Home Menu simply doesn't have this capacity.

Closed as rejected.
