### ISSUE TITLE
Anemone loads for a sec then the console crashes.

### ISSUE THREAD

**Issue by Fish-and-Chips** [astronautlevel2/Anemone3DS#246]
Exactly what the title says. Anemone loads for a sec then the console crashes.I tried deleting and reinstalling and deleting the 000002cd file but nothing.

edit:
The same issue happens when i tried to use another theme manager.

**Comment by Helloman892** [comment]
After some discussion on Discord, we have concluded that this problem occurs to @Fish-and-Chips with multiple different, seemingly distinct applications.
