### ISSUE TITLE
Anemone won't find the currently installed theme

### ISSUE THREAD

**Issue by barroer** [astronautlevel2/Anemone3DS#254]
Hey! I recently updated a hacked old 3DS to the latest Luma version, and before updating it I already had a theme there. The thing is, I want to transfer this theme to another device, but now that I have updated the 3DS, I can't find the theme file in the SD card nor on Anemone, as nothing shows up on the Anemone app when I use it. I can't find the theme online either btw.

This happens on an Old 3DS on the 11.14.0 version, Anemone v2.2.0 and Luma3ds v.10.2.1. Video attached.

https://user-images.githubusercontent.com/86318526/122974051-2dae0f80-d392-11eb-8227-180ab25066d2.mp4

**Comment by Helloman892** [comment]
Hi there,

There is a 'dump theme' feature in Anemone as of the latest version ([v2.2.0](https://github.com/astronautlevel2/Anemone3DS/releases/latest)), which you can access under the Extra menu by holding X.

Closing as invalid.
