### ISSUE TITLE
This software has conflict with the offical music player.

### ISSUE THREAD

**Issue by Manaka-Nemu** [astronautlevel2/Anemone3DS#256]
After using it to install a theme no matter with or without bgm, the offical music player will work abnormally. It can't search music folders correctly and get stuck in searching over and over again. After several minutes pressing home makes it crash. Switching back to default theme is useless. To rescue the music player, we need to delete the storage of main menu（X:/Nintedo 3DS/(32 bit ID)/(32 bit ID)/extdata/00000000/(local code)）.

![IMG_0178](https://user-images.githubusercontent.com/62064698/126833881-0add91b8-3608-4b9c-a02f-bf60e1233b2c.JPG)
![IMG_0177](https://user-images.githubusercontent.com/62064698/126834039-b4767c38-3a98-4cca-9061-6715ce9f5809.JPG)

**System information**
*System model* 3DS

*System firmware version* 11.14.0

*Anemone3DS version* v2.2.0 

*Luma3DS version* v10.2.1

**Comment by Helloman892** [comment]
Neither myself nor @LiquidFenrir can replicate this. However, we have only attempted this on EU region consoles, so we're not ruling out this being JP-specific.

Can you replicate this consistently, with multiple different themes?

**Comment by Helloman892** [comment]
Closed due to inactivity.
