### ISSUE TITLE
not remove splash after delete

### ISSUE THREAD

**Issue by ro23386** [astronautlevel2/Anemone3DS#257]
Hi there,

I have deleted a splashscreen image from menu, but it still loads splah. Disable it on luma do not return to new 3ds intro. Also I do not know if is possible to boot intro regular intro and after display splash screen ... after payload options on luma only display splash screen.

device info: new 3ds
software info: anemone3ds v2.2, luma v10.2.1, fbi 2.6.1 system version 11.14.0
setings luma: splash (after payloads; 1s);  (enable game patching) (show gba boot in patched AGB_FIRM)

steps: open anemone > scan qr code for splah > test/reset device > delete (B) splash >black screen at start > open anemone scan qr code for splah > test/reset device > delete from  SD (select) > test/reset device > previous splash screen display

By the way, nice project!

**Comment by Helloman892** [comment]
I won't make an excuse for not answering this months ago, but nonetheless:

As far as I am aware, the before/after payload options in Luma3DS's config are the timings around when you can hold a button to chainload a payload. In short, if you have it set to 'Before', you'll always see the splash, and if you have it set to 'After', you'll see it only when you load Luma3DS (i.e. you don't chainload anything).

I do not believe it possible to show both the default intro and the splash screen.

Besides that, if disabling it on Luma doesn't return to the default intro, I don't know what to tell you -- that isn't anything to do with Anemone, as all we do is move two files around to directories that have nothing to do with the 3DS itself.
