### ISSUE TITLE
How do i change the burtiok for scan qr code?

### ISSUE THREAD

**Issue by gergthewerg** [astronautlevel2/Anemone3DS#266]
My R button is broken so I can't scan qr codes. Is there a way to change the button? Thanks!

**Comment by gergthewerg** [comment]
And yes I did buy new buttons but ebay says may30th :|

**Comment by astronautlevel2** [comment]
There is no way to change the buttons without recompiling the application, if you are willing to recompile it you can edit this line: https://github.com/astronautlevel2/Anemone3DS/blob/master/source/main.c#L449
