### ISSUE TITLE
Theme is not loading

### ISSUE THREAD

**Issue by 99powerbreaker** [astronautlevel2/Anemone3DS#271]
**Description**
When attempting to install a theme, it does not load it. I have tried with two different themes, and this has been a recurring issue. 

**Steps to reproduce**
***If you cannot reproduce the bug, please describe what you were doing in as much detail as possible***
Look at the video, but I have attempted to install the theme. No matter what theme I use, it does not load the theme. 

**Expected behavior**
I expect that the program would load a custom theme.

**Screenshots**
Video: https://user-images.githubusercontent.com/99379078/172241969-62e46eee-3aed-49a7-9db0-39d375ff5dd0.mp4 

**Crash dumps**
No crash.

**System information**
*System model* Old 3ds XL

*System firmware version* 11.15.0-47U

*Anemone3DS version* v2.3.0

*Luma3DS version* e.g. v10.3-d5f32e30-3gxldr 

Extra info:
Enable Game patching is on, and Enable loading external FIRMs and modules is on in Luma3ds.
I have a 64GB SD card.

**Comment by 99powerbreaker** [comment]
This is still persisting. 
![image](https://user-images.githubusercontent.com/99379078/193376930-92e0129a-87a7-4dfb-9a10-f58796679c31.png)
This is the contents of the themes folder. 
I have also checked and Have the newest version of Godmode9.
I have old themes but do not have any of them currently selected. 
![image](https://user-images.githubusercontent.com/99379078/193377119-931bbd9c-cef9-468d-aeef-d687a8b7d858.png)
this is the contents of the lugia theme. 
This issue has persisted. I have the same configuration as before. Is there any known compatibility issues that would cause issues?
I have also reinstalled Anemone3DS. I removed it through the System Settings, and re-added it through FBI.
System Model: Old 3ds XL
System firmware version: 11.16.0-49U
Anemone3DS version: v2.3.1
Luma3DS version: v11.0
Additional Information: same as before. Homebrew Launcher is Version 2.4. Any help would be greatly appreciated, as I have no clue what could be the issue.

**Comment by Ninku2020** [comment]
I was having this same problem and this is the solution that I found. 
Enable 'game patching' from luma .
To go to luma screen.. hold select and power on. Then select enable game patching.

**Comment by 99powerbreaker** [comment]
Issue still persists. I mentioned it already but I already have game patching enabled. I disabled it and reenabled it and there is still issues.

**Comment by evan** [comment]
I had this problem and it turned out my sdcard was bad, with unusually low read speeds.

**Comment by 99powerbreaker** [comment]
Problem fixed. I deleted the theme data (https://github.com/astronautlevel2/Anemone3DS/wiki/Known-Bugs) and then reformatted my sd card with 32kb cluster size. Works now without a hitch! (Wish it didn't take so long for me to realize XD)
