### ISSUE TITLE
Splash issue

### ISSUE THREAD

**Issue by AgentBlade4** [astronautlevel2/Anemone3DS#274]
When I install a splash screen and reboot my console the splash screen doesn’t appear not even when I completely turn it off and on against

**Comment by dafish7** [comment]
im glad  im not the only one, was very confused about why my splashes arent showing after boot, but theyre all there in the splashes folder and in the splaashes section of anemone

**Comment by Helloman892** [comment]
This issue has been closed, presumably because the issue creator found the
Luma3DS setting to enable splashes. Please see
https://github.com/LumaTeam/Luma3DS/wiki/Optional-features#config-menu-options
.
