### ISSUE TITLE
Some themes' BGMs dont load in the preview.

### ISSUE THREAD

**Issue by rubenguip** [astronautlevel2/Anemone3DS#275]
I noticed a couple of themes from theme plaza wont load the BGM in the preview of Anemone.

The themes are:
https://themeplaza.art/item/46942
https://themeplaza.art/item/7884

When installed they work correctly.

Another issue is that BGM for themes downloaded from the old 3dsthem.es also dont load (maybe because it doesnt have the ogg file in the folder?). They used to work on themely.

**Comment by Helloman892** [comment]
RE: old 3dsthem.es theme previews: yes, the missing OGG is exactly why it doesn't load, we don't have a bcstm player in Anemone (Themely did, IIRC). With regards to those previews not working, someone can take a look, but I'm 70% sure on first look that it's a problem with the `preview.ogg` files.

**Comment by Helloman892** [comment]
The themes are using mono `bgm.bcstm` files, which is problematic for other reasons, but this leads to the `bgm.ogg` file also being mono. We don't currently handle the case where they're mono (preferring instead to assume that well-made themes will use stereo audio), but we can in theory.
