### ISSUE TITLE
[Feature Request] Multi languages support

### ISSUE THREAD

**Issue by cooolgamer** [astronautlevel2/Anemone3DS#281]
Would be nice to support multi languages for people not undertanding well english (That was already the case for [Themely](https://github.com/ihaveamac/Themely)).

There's already [my french translated fork](https://github.com/cooolgamer/Anemone3DS-FR) and [this spanish translated fork](https://github.com/Robichani6-1/Anemone3DS-ES) (got removed for some reasons?).

As for getting new languages you can always use [Crowdin](https://crowdin.com/).

**Comment by Helloman892** [comment]
Hi there, we have already had this in the works (technically) since 2017: #80
