### ISSUE TITLE
Uninstalling a theme with Anemone bricked my 3DS device

### ISSUE THREAD

**Issue by DeepRest101** [astronautlevel2/Anemone3DS#282]
I installed a theme using anemone. I wanted to delete the theme and go back to original layout. After deleting the theme in anemone, I returned to the Home Screen, and found that theme still remained. At this point, touchscreen input and analog button input does not work. Requesting compensation for the bricked device.

**Comment by LiquidFenrir** [comment]
Deleting themes in anemone only deletes the zip file that contains the data that gets installed to the home menu.

The proper way to go back to normal is to use the home menu's theme screen and select any official one (even the simple colours).

See the wiki for the folder to delete if you get an error when turning on.

Anemone cannot make your touchscreen or circle pad unresponsive (except maybe by hanging when exiting, but then you just need to turn off the console by holding the power button for 10 seconds).

Anemone devs, as per the GPL license, are not responsible for any damage caused to your device by use or misuse of the software, though I don't speak for them nor am I their lawyer.

**Comment by DeepRest101** [comment]
I would like you to consider what has happened. Although everything you are telling is very technical and matter of fact, I am here to contradict that with my reporting of this issue. I had a perfectly good system until I tried deleting a theme using anemone, directly afterwards, my system is bricked. I fail to understand how others in the 3ds community cannot come to terms with, or understand the issue that I am reporting. I have no ulterior motive.

**Comment by DeepRest101** [comment]
> Deleting themes in anemone only deletes the zip file that contains the data that gets installed to the home menu.
> 
> 
> 
> The proper way to go back to normal is to use the home menu's theme screen and select any official one (even the simple colours).
> 
> 
> 
> See the wiki for the folder to delete if you get an error when turning on.
> 
> 
> 
> Anemone cannot make your touchscreen or circle pad unresponsive (except maybe by hanging when exiting, but then you just need to turn off the console by holding the power button for 10 seconds).
> 
> 
> 
> Anemone devs, as per the GPL license, are not responsible for any damage caused to your device by use or misuse of the software, though I don't speak for them nor am I their lawyer.

Thank you for your quick response. Please take into consideration.

**Comment by LiquidFenrir** [comment]
It ain't bricked, just turn it off and turn it back on again. Calm down, listen, and all will go well.

**Comment by DeepRest101** [comment]
Turning the system on and off does nothing to fix the issue, thank you for the reassurance. Others in this community are not as kind. 

I can boot into godmode9, Rosalina etc. The analog button inputs work fine when I'm using the homebrew apps or custom firmware. 

Booting normally without holding start or select, the touchscreen is unresponsive and my system no longer registers any button inputs, except for "a" which can only be used to open anemone.

**Comment by LiquidFenrir** [comment]
Do try going into the SYSNAND SD menu with GM9, and deleting those specific folders inside `extdata/00000000` (depending on your console's region), then rebooting. This will delete all the installed theme info and make the home menu generate new ones.

JPN / USA / EUR:
- 00000082 / 0000008f / 00000092
- 000002cc / 000002cd / 000002ce

**Comment by DeepRest101** [comment]
I followed your instructions and was successful in deleting the old themes. 

After rebooting, my devices theme is back to normal, however there is still an issue with responsiveness. 

The only button that works is the "A" button, and using that I was able to launch a copy of Mario Kart 7. Playing the game, all of the controls are working and so is the touchscreen. 

However in the home menu it is still completely unresponsive except when I use the "A" button to launch the game.

**Comment by DeepRest101** [comment]
> Do try going into the SYSNAND SD menu with GM9, and deleting those specific folders inside `extdata/00000000` (depending on your console's region), then rebooting. This will delete all the installed theme info and make the home menu generate new ones.
> 
> 
> 
> JPN / USA / EUR:
> 
> - 00000082 / 0000008f / 00000092
> 
> - 000002cc / 000002cd / 000002ce

Thank you for the help you've been providing me thus far.

**Comment by DeepRest101** [comment]
Just to add some clarification, after following instructions and rebooting, the home menu cursor automatically lands on the icon for Mario Cart 7. At this point the only input my device registers is the "a" button, which then runs my copy of Mario Kart 7. If I press the home button during game play, I can use "X" to close the game. Other than this, my device is still unresponsive.

**Comment by DeepRest101** [comment]
Update

Periodically, after playing Mario Kart 7 and then returning to the Home menu, my touchscreen will become responsive again, but only briefly. I've been able to recreate this effect by playing through which ever game I can somehow manage to select whenever I have some form of response from the device. I was able to get full responsiveness for about 20 seconds before it went away.

**Comment by LiquidFenrir** [comment]
Well now it can't be anemone's fault anymore, so off to NH (Nintendo Homebrew) on discord you go. They'll be much more suited to help for this.

https://discord.gg/MWxPgEp

**Comment by astronautlevel2** [comment]
As fenrir said, this issue tracker is not for troubleshooting issues unrelated to Anemone3DS. The fact that your 3DS started exhibiting issues after using Anemone3DS is purely coincidental - the issues you described cannot possibly come from Anemone3DS (as fenrir explained), and even if they could, with how many people use Anemone3DS we would have heard a report about it before now.

**Comment by DeepRest101** [comment]
Just wanted to let you know how useless the discord is. I got the most help by complaining about my issue on github. The people on the discord channel are adamant that it's a hardware issue, that's if I'm lucky enough to get them to notice me.
