### ISSUE TITLE
Issue with QR Scanner

### ISSUE THREAD

**Issue by Artemis-782** [astronautlevel2/Anemone3DS#283]
**Description**
When opening the QR scanner the top screen is obscured by random yellow lines, the camera is still visible in the small unobscured spaces

**System information**
*System model* e.g. new3DS XL

*System firmware version* v11.16.0-49E

*Anemone3DS version* v2.3.1

*Luma3DS version* v12.0

**Comment by Helloman892** [comment]
This sounds like a hardware issue. Can you check the built in 3DS Camera app to see if it also exhibits this behaviour?

**Comment by Helloman892** [comment]
Closed as stale.
