### ISSUE TITLE
Anemone does not work after installing a eshop theme

### ISSUE THREAD

**Issue by Juggerpotato935** [astronautlevel2/Anemone3DS#284]
i was checking the 3ds theme shop just for curiosity and stumbled upon a free persona Q theme, as i am a fan of the persona series i wanted to try it out, but when i wanted to go back to my previous theme it just wouldn't work, it just puts the default white theme, and now even if i install the official themes from the store after i reset it goes back to the default white, i've tried a lot of things without success, i activated game patching in luma, deleted the extdata folder, reinstalled anemone, deleted and re-donloaded the theme, tried out different themes and installed them while using one of the default themes, formatted my sd card and loaded all of its data again and nothing has worked, i have the black old 3DS with the latest firmware update (11.16.0) and a 32GB MicroSD card with an adapter, i've got the latest anemone update and my luma update it's v12.0 please help me.

Also this doesn't produce a crash dump because the console itself doesnt crash really

**Comment by Helloman892** [comment]
Hi @Juggerpotato935, you're likely to get faster support asking in our support forum in the Theme Plaza Discord: https://discord.gg/FThVmGvn

**Comment by Helloman892** [comment]
Closed as stale.
