### ISSUE TITLE
"FS Error: Get a new SD Card." special character *

### ISSUE THREAD

**Issue by MaartenMan123** [astronautlevel2/Anemone3DS#288]
**Description**
This is a bug that came up on two separate systems: a N2DSXL and a N3DSXL. Error occurred upon attempting to download themes with the title containing DECO*27. Probably an error clashing with the special character '*'.

**Steps to reproduce**
[https://themeplaza.art/item/42401](url) <<< the link to the theme.
How to reproduce: try downloading this theme, or any theme with the name DECO*27, either through the QR scanner or by downloading it from Anomone's in-app browser.

**Expected behavior**
Not getting an error message, or one that doesn't result in 'Get a new SD Card'.

**Screenshots**
![photo_2023-04-25_19-03-36](https://user-images.githubusercontent.com/80426816/234351544-6bafa382-626c-4d99-8357-91ec6bc79e4d.jpg)
![photo_2023-04-25_19-03-33](https://user-images.githubusercontent.com/80426816/234351547-4ca85e9d-ea98-4bdd-9dfd-044c8b47e126.jpg)

https://user-images.githubusercontent.com/80426816/234351548-e7210792-cfc3-49c2-9417-38b101f27afc.mp4

**Crash dumps**
It doesn't. Just an error message.

**System information**
*System model* new3DS XL & new2DS XL

*System firmware version* 11.16.0-49J

*Anemone3DS version* v2.3.1

*Luma3DS version* v11.0

**Comment by Helloman892** [comment]
This is a known issue: #267. If I find a moment I'll produce a build that should fix this problem, and also it'll be wrapped up into the next release (whenever that happens).
