### ISSUE TITLE
Screen glitching after shuffle used.

### ISSUE THREAD

**Issue by TabbyXALT** [astronautlevel2/Anemone3DS#291]
I recently bought a used new 3ds xl, but today, I decided to shuffle 4 themes. It glitched my screen and I don’t know how to fix it.
![59CBBBAF-8EA8-4822-8F23-BB77220A3BD7](https://github.com/astronautlevel2/Anemone3DS/assets/134968964/364a6cec-6c80-4b5a-b616-208f2c69e159)
(Please note that the glitch only occurs when the screen is closing, not when it’s locked in place.)

I’m using all the current firmware, but I deleted anemone to see if it would fix it. If you have a solution to my problem, it would be very helpful.

**Comment by TabbyXALT** [comment]
I’m also kinda desperate because this is the first time I’ve modded something, and it makes me look like an irresponsible idiot.

**Comment by oreo639** [comment]
> Please note that the glitch only occurs when the screen is closing, not when it’s locked in place

This sounds like a hardware issue. (i.e. with the screen cable)

**Comment by TabbyXALT** [comment]
> > Please note that the glitch only occurs when the screen is closing, not when it’s locked in place
> 
> This sounds like a hardware issue. (i.e. with the screen cable)

But it’s weird that it only started happening after I used the shuffle feature. I guess I’ll just have to live with it.
