### ISSUE TITLE
Error in HTTPC sysmodule - 0xd8a0a046

### ISSUE THREAD

**Issue by Rodgebrick** [astronautlevel2/Anemone3DS#298]
I am trying to download a theme and not matter what theme I try to download I get this error message.

**Comment by Helloman892** [comment]
This is not a support forum; you can find support on the Theme Plaza Discord server at https://discord.gg/2hUQwXz.

For this specific problem, you have one of two things wrong: either you have no WiFi signal or you have a custom DNS set. If you don't know what that means, please ask for further help in the support forum on the Discord.
