### ISSUE TITLE
[Bug] Japanese named themes breaks while downloaded on anemone

### ISSUE THREAD

**Issue by cooolgamer** [astronautlevel2/Anemone3DS#303]
**Description**
Downloading a theme with Japanese characters breaks the theme file until renamed
The theme itself downloads fine and is fine itself, but gets a weird name that make it unusable on anemone

**Steps to reproduce**
Download a theme with Japanese characters like this one: https://themeplaza.art/item/80790 using QR scanner or themeplaza browser

**Expected behavior**
The theme should be named as the theme name

**Screenshots**
The downloaded theme have a weird name and is not usable on anemone:
![image](https://github.com/astronautlevel2/Anemone3DS/assets/64099608/971beb7d-ab5b-43f5-addc-e1518529db73)
![image](https://github.com/astronautlevel2/Anemone3DS/assets/64099608/bd199a07-6c1b-438e-9111-08f3165a4047)

But the file itself is fine:
![image](https://github.com/astronautlevel2/Anemone3DS/assets/64099608/c9b6f5dc-08f9-4522-8007-3d76f7818f30)

**Crash dumps**
(No crash)

**System information**
Tried on n2DS XL and 3DS XL

*System firmware version* e.g. 11.14.0 (this can be found in the System Settings applet by default)
11.17.0-50E

*Anemone3DS version* e.g. v2.2.0 (found in the bottom-left of Anemone3DS)
v2.3.1, I compiled the latest commits and changed the color, this bug also apply on the releases build

*Luma3DS version* e.g. v10.2.1 (found in the menu when you hold Select on boot)
v13.0.2

**If you are not on the [latest version of Anemone3DS](https://github.com/astronautlevel2/Anemone3DS/releases/latest), your bug report will likely be closed. Ensure the bug occurs in the latest build!**

**Comment by astronautlevel2** [comment]
Probably something with the encoding downloaded from Theme Plaza being different than what Anemone is expecting

@Helloman892 Do you have any insights into this? If not I'll try to replicate it this weekend.

**Comment by astronautlevel2** [comment]
Unsurprisingly Anemone was assuming ASCII even though the encoding was UTF-16 - we'll have a new release soon once we close a couple more issues. If you build the latest commit it should work properly.
