### ISSUE TITLE
System crashing during jump

### ISSUE THREAD

**Issue by Cloner-Crashing** [astronautlevel2/Anemone3DS#304]
Whenever I attempt to jump through themes (by using X+dpad up and entering a number), the system almost always crashes upon attempting to execute. I've tried this with both many and few themes installed to the SD, and it crashed all times. Clicking cancel doesn't cause a crash if that's helpful. 

Crash details: 
"
An exception occurred

Processor: Arm11 (core 0)
Exception type: data abort
Fault status: Translation - Section
Current process: Anemone3 (00400000BAFE000)
"

It also lists a number of register info and the stack dump that I won't bother transcribing. I saved a few of the crash dumps, and will upload and attach one to this. 

The jump _did_ work on very rare occasions, namely when I entered "12" or "8" from spot 1, 24 from spot 12, 20 from 8, 
It still crashed when entering 48 from 24, or 40 from 20. 

Any suggestions for how to fix this would be helpful.

[crash_dump_00000001.dmp](https://github.com/astronautlevel2/Anemone3DS/files/15211152/crash_dump_00000001.dmp)

**Comment by astronautlevel2** [comment]
The crash seems to be happening when deleting the texture storing the icon - could you upload the themes you're testing with?

**Comment by Cloner-Crashing** [comment]
Uploading a set of the themes I use. Generally it seems to occur shortly after I have ~30 themes on the device, rather than any one theme in particular that I've noticed. I often have more on the device, but I was using a smaller number atm. 

Also of note, I am using a 128 GB microsd formatted FAT32 in my 2ds xl, in case that causes any problems with your software. 

[3dsthemes_mintest3.zip](https://github.com/user-attachments/files/15524033/3dsthemes_mintest3.zip)
[3dsthemes_mintest2.zip](https://github.com/user-attachments/files/15524032/3dsthemes_mintest2.zip)
[3dsthemes_mintest1.zip](https://github.com/user-attachments/files/15524030/3dsthemes_mintest1.zip)
[3dsthemes_mintest4.zip](https://github.com/user-attachments/files/15524037/3dsthemes_mintest4.zip)
[3dsthemes_mintest5.zip](https://github.com/user-attachments/files/15524041/3dsthemes_mintest5.zip)
[3dsthemes_mintest6.zip](https://github.com/user-attachments/files/15524043/3dsthemes_mintest6.zip)

Should be 41 themes there, split into multiple zips because the website is only allowing me to upload 25 MB or smaller files.

**Comment by astronautlevel2** [comment]
Are you using an old 3ds or new 3ds? I'm unable to replicate this on my new 3ds but do not have an old 3ds to test with.

**Comment by astronautlevel2** [comment]
Can you test the most recent commit?
[Anemone3DS.cia](https://cdn.discordapp.com/attachments/679907001010094151/1250469970010443917/Anemone3DS.cia?ex=666b0e69&is=6669bce9&hm=4335378dff89da4d3c53f88932941bb3b3599627b426a95d9755cdff7687a7b9&)
[Anemone3DS.3dsx](https://cdn.discordapp.com/attachments/679907001010094151/1250469970433937459/Anemone3DS.3dsx?ex=666b0e69&is=6669bce9&hm=ffe1223620d7264203b6e98add970173cfd658fc37a92a74378e79696f032080&)

**Comment by astronautlevel2** [comment]
Fixed in 4669f13
