### ISSUE TITLE
Suggestion: Custom Configuration

### ISSUE THREAD

**Issue by Darkshadow3582** [astronautlevel2/Anemone3DS#31]
Maybe you could also make me read the themes and splashes from another location?

More specifically in the same folder where the .3dsx is saved as
3ds/Anemone3DS/(here Theme folder and splash folder)
or in the folder
3ds/data/Anemone3DS/(here Theme folder and splash folder)

**Comment by ZetaDesigns** [comment]
It's already planned to have a custom path to themes, but for now we only want to have it on the root, since thats easier for most people.

**Comment by astronautlevel2** [comment]
In addition to custom paths, I also plan to allow custom colors for the theme manager.

**Comment by astronautlevel2** [comment]
Paths added in 79afaca.

Some more work on colors remaining - specifically splitting off the multiple different ways white is currently used into context sensitive colors.

**Comment by astronautlevel2** [comment]
(Tentatively) finished in [1418c2b](https://github.com/astronautlevel2/Anemone3DS/commit/1418c2bc8dbee2cc2f0c4038afd969601979d8da)
