### ISSUE TITLE
[FEATURE REQUEST] Color switching

### ISSUE THREAD

**Issue by taserbolt** [astronautlevel2/Anemone3DS#322]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
A settings menu where you can change the color of the blue bars to something else, as well as an option to make it rainbow, where the colors change like you're slowly sliding the cursor in a color picking menu STARTING FROM the [12, 58, 111] default blue (see image).

**Describe alternatives you've considered**
just let us change the sidebars between six color options: Default blue, red, orange, yellow, green, and purple

**Additional context**
![image](https://github.com/astronautlevel2/Anemone3DS/assets/170961732/ae322358-91bc-4353-94a7-dcc3a2a0505c)
![image2](https://github.com/astronautlevel2/Anemone3DS/assets/170961732/2019f7f2-b0a3-438f-9bca-2288355e63db)

**Comment by astronautlevel2** [comment]
This is included in Issue #31 (Custom Configuration)
