### ISSUE TITLE
Ext Data Locked with Badges 

### ISSUE THREAD

**Issue by PandaPandel** [astronautlevel2/Anemone3DS#323]
**Description**
I added subfolders to the badges folder, But I deleted the original badges folder on SD to move a new file structure into it. 

Then I moved the new badges folder and when i tried to install I got arm11 error and also Locked EXT data.

**Steps to reproduce**
Deleting your badges folder and then adding a new one. Idk what I did. 

**Expected behavior**
I think it was supposed to over ride the old EXT data, Maybe an issue with having GYBT still installed not sure

**Screenshots**
Add screenshots of any error screens you encountered. Bug reports without screenshots will take longer to solve, so we recommend you get some!

**Crash dumps**
If your bug causes a crash in Luma3DS, please upload any crash dumps generated. You can find these in `SD:/luma/dumps/armX` (`X = 9 or 11`) with the name Luma3DS's exception handlers give you.

**System information**
*System model* e.g. new3DS XL

*System firmware version* e.g. 11.14.0 (this can be found in the System Settings applet by default)

*Anemone3DS version* e.g. v2.2.0 (found in the bottom-left of Anemone3DS)

*Luma3DS version* e.g. v10.2.1 (found in the menu when you hold Select on boot)

**If you are not on the [latest version of Anemone3DS](https://github.com/astronautlevel2/Anemone3DS/releases/latest), your bug report will likely be closed. Ensure the bug occurs in the latest build!** Latest build 3.0.0

**Comment by astronautlevel2** [comment]
Can you upload the arm11 exception? It should be on your SD card in /luma/dumps/arm11

**Comment by Usag1Knight83** [comment]
To delete gytb's extdata, hold L+R+X+Y when it's starting from the Nintendo 3ds loading screen to bring up a hidden screen asking if you want to delete it's extdata. After doing that, you should see that attempting to press the Decorate with Badges button will say you don't have any badges.

**Comment by PandaPandel** [comment]
> To delete gytb's extdata, hold L+R+X+Y when it's starting from the Nintendo 3ds loading screen to bring up a hidden screen asking if you want to delete it's extdata. After doing that, you should see that attempting to press the Decorate with Badges button will say you don't have any badges.

I will try this. Thanks for the tip.

**Comment by PandaPandel** [comment]
> Can you upload the arm11 exception? It should be on your SD card in /luma/dumps/arm11

I was mistaken it actually isn't an arm 11 exception it's a ErrDisp, it doesn't seem to dump  a .dmp

Here's a clip of what happens:

**Comment by PandaPandel** [comment]
![20240615_034714](https://github.com/astronautlevel2/Anemone3DS/assets/167732157/f2ec4f97-2a38-48c4-aa05-530800c0ce63)

**Comment by PandaPandel** [comment]
After deleting the ext data with that secret code, the ext data still says it's locked using the subfolder system 
![20240616_005252](https://github.com/astronautlevel2/Anemone3DS/assets/167732157/f3933577-ccad-4afc-a2c5-1ea6462a1faa)
![20240616_005511](https://github.com/astronautlevel2/Anemone3DS/assets/167732157/93dbf81c-3432-4836-8919-255c79be033f)

**Comment by PandaPandel** [comment]
> To delete gytb's extdata, hold L+R+X+Y when it's starting from the Nintendo 3ds loading screen to bring up a hidden screen asking if you want to delete it's extdata. After doing that, you should see that attempting to press the Decorate with Badges button will say you don't have any badges.

![20240616_010523](https://github.com/astronautlevel2/Anemone3DS/assets/167732157/721ab129-7776-4603-a6b8-a62eb02f3763)

It definitely worked, I just can't seem to get further from here

**Comment by astronautlevel2** [comment]
Can you zip up your /Badges/ folder and upload it, either here, over GBATemp, or over Discord?

**Comment by astronautlevel2** [comment]
[e613a52](https://github.com/astronautlevel2/Anemone3DS/commit/e613a525a5aea4b450f168ded0b544074afeef0d) should fix this - can you try this build and see if it works?

[Anemone3DS.cia](https://cdn.discordapp.com/attachments/355865390074560513/1252275929066242149/Anemone3DS.cia?ex=6671a057&is=66704ed7&hm=1fbf351b0bd58adc290e00a9b31b136ba389535c9c011593267f3a380bdf6a5f&)
[Anemone3DS.3dsx](https://cdn.discordapp.com/attachments/355865390074560513/1252275929334550528/Anemone3DS.3dsx?ex=6671a057&is=66704ed7&hm=005d949d192683e6f84681443975132afb2a77128bea97326a1fad9c7221e539&)
![](https://media.discordapp.net/attachments/355865390074560513/1252275937265975409/Anemone3DS.cia_qr.png?ex=6671a059&is=66704ed9&hm=5e5a2c407bae4c718ddc9e778fc3fb72eecedb279d81e5fadd478593d467a3b3&=&format=webp&quality=lossless&width=400&height=433)

**Comment by PandaPandel** [comment]
Let me give this a shot, I wil install this first, if it does not work, I will zip my badges.

**Comment by PandaPandel** [comment]
> [e613a52](https://github.com/astronautlevel2/Anemone3DS/commit/e613a525a5aea4b450f168ded0b544074afeef0d) should fix this - can you try this build and see if it works?
> 
> [Anemone3DS.cia](https://cdn.discordapp.com/attachments/355865390074560513/1252275929066242149/Anemone3DS.cia?ex=6671a057&is=66704ed7&hm=1fbf351b0bd58adc290e00a9b31b136ba389535c9c011593267f3a380bdf6a5f&) [Anemone3DS.3dsx](https://cdn.discordapp.com/attachments/355865390074560513/1252275929334550528/Anemone3DS.3dsx?ex=6671a057&is=66704ed7&hm=005d949d192683e6f84681443975132afb2a77128bea97326a1fad9c7221e539&) ![](https://camo.githubusercontent.com/4a31d7996f86dfee8a8feff3dbb6bb63f8ec55a7ae893e69f98de8eebc9a4d17/68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f3335353836353339303037343536303531332f313235323237353933373236353937353430392f416e656d6f6e653344532e6369615f71722e706e673f65783d36363731613035392669733d363637303465643926686d3d35653561326334303762616534633731386464633965373738666333666237326565636564623237396438316535666164643437383539336434363761336233263d26666f726d61743d77656270267175616c6974793d6c6f73736c6573732677696474683d343030266865696768743d343333)

This build hot fix fixed the issue! I was able to press X, and hit the badge button to install badges. 

Drop down menu works now for badges again, and Sub folder system works like a charm now! <3 Nice going girl!

**Comment by astronautlevel2** [comment]
Great! Thanks for your help testing.

Closing as fixed by [e613a52](https://github.com/astronautlevel2/Anemone3DS/commit/e613a525a5aea4b450f168ded0b544074afeef0d)

**Comment by PandaPandel** [comment]
> Great! Thanks for your help testing.
> 
> Closing as fixed by [e613a52](https://github.com/astronautlevel2/Anemone3DS/commit/e613a525a5aea4b450f168ded0b544074afeef0d)

So happy to help test since I've got my 3ds on my desk for all the theme creations! It's the least I can do. 

This release is so amazing! Fantastic job to you and the team for this. 🌈🥺❤️
