### ISSUE TITLE
Not finding the downloaded badges

### ISSUE THREAD

**Issue by AirConditionunit** [astronautlevel2/Anemone3DS#324]
Edit: I found it by just pressing a random button but it does reset all my badges

Old: T̶h̶e̶ ̶B̶a̶d̶g̶e̶s̶ ̶i̶ ̶d̶o̶w̶n̶l̶o̶a̶d̶e̶d̶ ̶u̶s̶i̶n̶g̶ ̶t̶h̶e̶ ̶A̶n̶e̶m̶o̶n̶e̶3̶D̶S̶ ̶a̶p̶p̶ ̶i̶s̶ ̶n̶o̶t̶ ̶s̶h̶o̶w̶i̶n̶g̶ ̶i̶n̶ ̶m̶y̶ ̶b̶a̶d̶g̶e̶s̶ ̶a̶n̶d̶ ̶t̶h̶e̶r̶e̶'̶s̶ ̶n̶o̶ ̶s̶e̶c̶t̶i̶o̶n̶ ̶f̶o̶r̶ ̶i̶t̶ ̶i̶n̶ ̶t̶h̶e̶ ̶a̶p̶p̶ ̶l̶i̶k̶e̶ ̶t̶h̶e̶ ̶s̶p̶l̶a̶s̶h̶ ̶s̶c̶r̶e̶e̶n̶s̶ ̶a̶n̶d̶ ̶t̶h̶e̶m̶e̶'̶s̶,̶ ̶i̶'̶m̶ ̶u̶s̶i̶n̶g̶ ̶t̶h̶e̶ ̶l̶a̶t̶e̶s̶t̶ ̶v̶e̶r̶s̶i̶o̶n̶ ̶i̶n̶ ̶e̶v̶e̶r̶y̶t̶h̶i̶n̶g̶ ̶(̶F̶i̶r̶m̶w̶a̶r̶e̶,̶ ̶A̶n̶e̶m̶o̶n̶e̶3̶D̶S̶)̶

**Comment by astronautlevel2** [comment]
Please read the badge instructions on the wiki: https://github.com/astronautlevel2/Anemone3DS/wiki/Badges
