### ISSUE TITLE
New 3ds xl crashes when dumping Badge collection

### ISSUE THREAD

**Issue by superman055** [astronautlevel2/Anemone3DS#325]
**Description**
New 3ds Xl model crashes when i try and dump current badge collection.

**Steps to reproduce**
Enter dumping menu and press left to dump badges.

**Expected behavior**
3ds dumps installed badges.

**Screenshots**
![20240616_051853](https://github.com/astronautlevel2/Anemone3DS/assets/48631729/217abc7a-7052-436d-bcc8-a5ae500d3dbe)

**Crash dumps**
[crash_dump_00000002.dmp](https://github.com/user-attachments/files/15857253/crash_dump_00000002.dmp)

**System information**
new3DS XL

*System firmware version* 11.17.0-50U

*Anemone3DS version* v3.0.0

*Luma3DS version* v13.1.1

**Comment by astronautlevel2** [comment]
Can you dump your badge extdata with SBI and send me the BadgeMngFile.dat and BadgeData.dat? They'll be on your SD card at /3ds/SimpleBadgeInjector/Dumped

**Comment by superman055** [comment]
No problem here are the files sorry its in zip format github wouldnt let me upload the files normally
[Badge_etx_data.zip](https://github.com/user-attachments/files/15874252/Badge_etx_data.zip)

**Comment by astronautlevel2** [comment]
Can you try this build?

[Anemone3DS.cia](https://cdn.discordapp.com/attachments/1252128220187459585/1252324564357353472/Anemone3DS.cia?ex=6671cda3&is=66707c23&hm=b4ed74a33f2050f8ee46f41cdbf1a4d3bd8c571d0b98cd9b3e0a985eb0d6189a&)
[Anemone3DS.3dsx](https://cdn.discordapp.com/attachments/1252128220187459585/1252324564701155460/Anemone3DS.3dsx?ex=6671cda3&is=66707c23&hm=1553ca4db2b2b7a36ed3bd8d27f40e6b2dd9b913dd59ac9d1f9af784d82dcf40&)

**Comment by superman055** [comment]
The .cia version worked however the .3dsx version says the ext data is locked with the debug code 0xc92044e6

**Comment by superman055** [comment]
Oh cool im getting a issue where dumping the badges through generates some invalid file names for set folders though

**Comment by astronautlevel2** [comment]
Can you describe the invalid characters?

**Comment by superman055** [comment]
Im getting the issue with these sets specfically where i cant open the folder or even delete them on windows again linux works fine

![image](https://github.com/astronautlevel2/Anemone3DS/assets/48631729/ec861011-d20f-462a-a448-af2df15652f6)

**Comment by astronautlevel2** [comment]
Is it all of these sets?

**Comment by astronautlevel2** [comment]
Anemone doesn't clear the badge backup folder automatically so make sure you're actually checking the new folders

**Comment by superman055** [comment]
Double checked and they are still invalid names for the folders on windows but here is how the names appear in the linux path if that means anything (Comparing a folder that doesnt open or delete on windows "Pokémon - Kalos Region
-(National Pokédex No-650～)" to one that will "The Legend of Zelda- Majora's Mask 3D"

![Screenshot from 2024-06-17 16-26-32](https://github.com/astronautlevel2/Anemone3DS/assets/48631729/f638d12d-8e54-4259-9693-44f1a66337d5)

![Screenshot from 2024-06-17 16-27-49](https://github.com/astronautlevel2/Anemone3DS/assets/48631729/38db970e-c07e-4e21-9453-f9e949267d11)

**Comment by astronautlevel2** [comment]
Thanks for your patience - it looks like the file name had both a newline and a carriage return in it. 

Last ones, hopefully:
[Anemone3DS.3dsx](https://cdn.discordapp.com/attachments/679907001010094151/1252363609602785371/Anemone3DS.3dsx?ex=6671f200&is=6670a080&hm=6edb971546ac9df2d2fa25c04d0893ccb068c279892232bcbf9ec807e2a67a2f&)
[Anemone3DS.cia](https://cdn.discordapp.com/attachments/679907001010094151/1252363581241036911/Anemone3DS.cia?ex=6671f1f9&is=6670a079&hm=657330eaaaa80195cb9f4ca8bd5ce47b72ba8d2b5e586be7e864db89c83a8ab5&)

**Comment by superman055** [comment]
No worries and thank you for your patience - Everything appears to be accessable and working properly now

**Comment by astronautlevel2** [comment]
Closed by a8cc3eb
