### ISSUE TITLE
No warning when installing badges (erases everything)

### ISSUE THREAD

**Issue by Golem642** [astronautlevel2/Anemone3DS#329]
Ok so i accidentally pressed on install badges instead of dumping and it erased every badge I have without a warning or some kind of "rollback backup" planned.

Thankfully i already had a backup but someone unaware who did the same thing as me without a backup could be problematic

Could you please do something for this ? Thanks !

**Comment by astronautlevel2** [comment]
If you're on the latest version, a backup of your badge data would be made at /3ds/Anemone3DS/BadgeMngFile.dat & BadgeData.dat
