### ISSUE TITLE
More shuffle splashes; Theme browser

### ISSUE THREAD

**Issue by 1mcuadros** [astronautlevel2/Anemone3DS#34]
Hello, I don't know if it is possible somehow to have more than 10 shuffle themes at the same time, also, I don't know if it already has a splash shuffle option and if you could please add it? Besides you could add an option to download themes directly in the 3ds from a page.

Thanks and keep up the good work :D.

**Comment by astronautlevel2** [comment]
Hello - 

Unfortunately, having more than 10 shuffle themes at once is impossible. This is a limit imposed by Nintendo.

I plan to add support for shuffle splashes.

I'm working on implementing QR codes, and as a long term goal, a direct browser in the app itself.

**Comment by Helloman892** [comment]
Title edited to suit current content.
