### ISSUE TITLE
Error in shuffle mode

### ISSUE THREAD

**Issue by Ryumarubr** [astronautlevel2/Anemone3DS#36]
I had a little problem with shuffle mode, I installed 10 themes. Four Themes had the repeat loop disabled, the music only played once. Apparently this problem was only presented in the current version.

**Comment by Helloman892** [comment]
Hi, @Ryumarubr; does this still happen on the latest version?

**Comment by papermario69** [comment]
I have the latest .3dsx no cfw version, and the shuffle theme function is working fine. When I try to install a single theme, though, it freezes. Also, I figured this wouldn't work, but I tried the QR scanner and it crashed.

**Comment by Helloman892** [comment]
@papermario69 If when you say 'crash' you mean 'the screen froze', that's not a crash. All it is is the QR scanner not being drawn over during the theme download - this is a known inconvenience, and we'll fix it when we fix the current crash bugs we have [and yes, they exist].

**Comment by ZetaDesigns** [comment]
The QR Scanner now shows "Downloading..." if the QR has been read successfully.

**Comment by papermario69** [comment]
Ok I'll update mine and check. I don't know much about any of this stuff. You're the experts.

**Comment by papermario69** [comment]
QR scanner still freezing. Is there something other than the .3dsx version for that to work?

**Comment by astronautlevel2** [comment]
Hey @papermario69 - you're correct that the QR scanner does not work without CFW as of right now. The solution seems to be to take over an application other than DL Play, as DL Play doesn't have CAMU permissions.

In the mean time, I'm going to ask you to open a new issue for this, thanks!

@Ryumarubr I've tested applications in both this and Themely and haven't found cases in which Themely works and this doesn't. If you can provide a set of 10 themes that work with Themely and not this I'll reopen it.
