### ISSUE TITLE
Camera G & B channels swapped

### ISSUE THREAD

**Issue by Helloman892** [astronautlevel2/Anemone3DS#37]
As far as I can tell [and I can't find the function], the green and blue channels in the QR reader are swapped.  Attached is the QR reader's view of my X/Y 3DS case, which should obviously be blue.
~~fix this astro~~
![top_0001](https://user-images.githubusercontent.com/1565516/30022223-590985ae-9162-11e7-8548-2719e961595f.png)
NOTE: This is on commit `5fc499f`.

**Comment by astronautlevel2** [comment]
Angery

I knew _something_ looked off about the camera output but could never put my finger on it, figured it was just the 3DS being a POS. 

https://github.com/astronautlevel2/Anemone3DS/blob/master/source/draw.c#L73 Here's the function where it swaps the bytes around, try making b = *(byte_pointer) + 1 and g *(byte_pointer) + 2, that should swap the B and G channels.

**Comment by Helloman892** [comment]
solved by the above commits [ffs github]

**Comment by ZetaDesigns** [comment]
The camera now mostly has a green tint to it, but sometimes flashes to normal color.

**Comment by astronautlevel2** [comment]
I'll be home soon, will try to take a look.

**Comment by astronautlevel2** [comment]
Cannot replicate, looks fine here.

**Comment by Helloman892** [comment]
@astronautlevel2 @ZetaDesigns 
Sounds almost definitively like a hardware issue, considering that my initial screen (and this one) are both taken in Rosalina.
![top_0002](https://user-images.githubusercontent.com/1565516/30034983-38ef9ab6-919d-11e7-86b3-cb98a2894bf1.png)

**Comment by ZetaDesigns** [comment]
Certainly not a hardware issue.
Might be a difference between o3ds and n3ds?
http://imgur.com/a/JgkGz

**Comment by astronautlevel2** [comment]
What are you on?

Also follow up question, what's the lighting like?

**Comment by ZetaDesigns** [comment]
Am on o3ds and lightning is pretty bright, as seen in above picture.

**Comment by Helloman892** [comment]
Well, I tested on an N3DS - but let me check the QR reader again.

**Comment by ZetaDesigns** [comment]
They're on N3DS.

**Comment by astronautlevel2** [comment]
n3ds as well.

ihaveamac tested on his 2ds and got the green tint as well. Not sure what's causing this, will continue to look into it

**Comment by astronautlevel2** [comment]
Additionally, junko tested on a n2ds and had the same issue. However, the n2ds uses the o3ds cameras, so it definitely seems there's something weird going on.

**Comment by Helloman892** [comment]
Ok, so it's the camera. Could it be something to do with the FPS of the cameras?

**Comment by astronautlevel2** [comment]
Should be fixed in https://github.com/astronautlevel2/Anemone3DS/commit/03497a79efafb316585cb6b2c26f2b322479711c

@ZetaDesigns want to test?
[out.zip](https://github.com/astronautlevel2/Anemone3DS/files/1275288/out.zip)

**Comment by ZetaDesigns** [comment]
Yup, looks fine now.
