### ISSUE TITLE
Can't install ten themes at once.

### ISSUE THREAD

**Issue by jupitteer** [astronautlevel2/Anemone3DS#42]
I can install nine themes, but not ten. If I try to install ten, it very briefly flashes the installing theme shuffle screen and does nothing.

**Comment by Helloman892** [comment]
The error was a simple `<` vs. `<=`, if I'm not mistaken. I'll get back to you any minute with a build you can try, give me a couple.

**Comment by jupitteer** [comment]
Thank you.

**Comment by Helloman892** [comment]
Try this.
[Anemone3DS.zip](https://github.com/astronautlevel2/Anemone3DS/files/1275358/Anemone3DS.zip)

**Comment by jupitteer** [comment]
That build works. Thank you.
