### ISSUE TITLE
About translations

### ISSUE THREAD

**Issue by GreatWizard** [astronautlevel2/Anemone3DS#47]
What is the technical decision about setup translations?
If you use a standard tool like `gettext` it will be possible to use https://transifex.com/ or https://crowdin.com/ service to handle translation from contributors :)

I can help if you want

**Comment by astronautlevel2** [comment]
gettext looks interesting, I'll consider it. The main concern I have with it is it seems like each language is compiled to a different output, which doesn't really work in this case .

**Comment by GreatWizard** [comment]
I'm not sure to understand your concern.

There is like 20 strings to translate and in my experiences (website mostly), `gettext` did the job very well.

**Comment by astronautlevel2** [comment]
Closed (#80)
