### ISSUE TITLE
(Suggestion) A tool for sending themes directly from a PC to Anemone

### ISSUE THREAD

**Issue by jupitteer** [astronautlevel2/Anemone3DS#48]
This would greatly simplify testing themes and taking screenshots.

**Comment by Helloman892** [comment]
You can use QR codes already. Did you mean something more internal?

**Comment by jupitteer** [comment]
Yeah, something similar to 3dslink. Using ftpd is alright, but something like 3dslink would be great.

**Comment by astronautlevel2** [comment]
Netcode makes me sad
