### ISSUE TITLE
bricked my 3ds after closing during download

### ISSUE THREAD

**Issue by unknownaccount11** [astronautlevel2/Anemone3DS#53]
deleted themely, installed this, tried to install a theme from themely via the new qr code thingy. wouldn't show up so i restarted the ds and now it just boots into a black screen.

**Comment by Helloman892** [comment]
No, your DS is not bricked. @astronautlevel2 needs to see this.

**Comment by Helloman892** [comment]
I can't get to there at the moment, but if you head to https://discord.gg/C29hYvh and type `.homext` in one of the assistance channels, following the instructions given to you by Kurisu **should** fix your error.

**Comment by astronautlevel2** [comment]
You shut your 3ds off presumably while it was installing the theme data, which means that it corrupted your theme data. Do as helloman suggested and delete the home menu and theme extdata.
