### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Ryumarubr** [astronautlevel2/Anemone3DS#56]
You could add a function, which allows you to delete a selected theme.

**Comment by ZetaDesigns** [comment]
Delete a selected theme as in uninstall it or remove it from sdmc?

**Comment by Ryumarubr** [comment]
Delete it from SD.

**Comment by Helloman892** [comment]
Just as an update, I've defined the required function and will be adding a key combo for deletion by the next release.

**Comment by ZetaDesigns** [comment]
Closing this now.
