### ISSUE TITLE
cia not working

### ISSUE THREAD

**Issue by dumbledine** [astronautlevel2/Anemone3DS#59]
I'm not sure if this is just me but the app works fine from the homebrew launcher, but when I use the cia, the app opens but when I click install theme nothing happens

**Comment by daedreth** [comment]
Which release are you using?

**Comment by Helloman892** [comment]
There is no reason [in any released build] for that behaviour. The only reason this would happen is if you had built it yourself after a commit that broke something, and as far as I know [and I've tested every change I've made, at least] such doesn't exist.

Did you build an in-progress branch, or a fork?

**Comment by astronautlevel2** [comment]
Closing this as OP hasn't responded.
