### ISSUE TITLE
10-theme shuffle

### ISSUE THREAD

**Issue by CecilFF4** [astronautlevel2/Anemone3DS#61]
Using cia version of latest. Selecting 10 themes for shuffle and then trying to install them fails. No error. It very, very briefly flashes a message that they're being installed, but they don't. The previous themes don't get erased either by this action. Deselecting just one of them allows the install to proceed.

**Comment by ZetaDesigns** [comment]
This is a known bug. Use this release instrad:
[Anemone3ds.zip](https://github.com/astronautlevel2/Anemone3DS/files/1275358/Anemone3DS.zip)
