### ISSUE TITLE
Data Abort when theme extdata is not present

### ISSUE THREAD

**Issue by Helloman892** [astronautlevel2/Anemone3DS#63]
~~smh~~

Could someone test the latest `master`? I'm getting a data abort on boot regardless of filetype.

**Comment by Helloman892** [comment]
This was my own fault, I forgot that I reset my theme extdata

**Comment by astronautlevel2** [comment]
This still shouldn't cause an arm11 dabort, I'll fix it.

**Comment by ZetaDesigns** [comment]
This was "fixed", there is no dataabort anymore, but also no warning, ergo no themes would install.

**Comment by ZetaDesigns** [comment]
It now throws an error.
