### ISSUE TITLE
[Feature Request] Installed/Shuffle Indicator

### ISSUE THREAD

**Issue by greenDarkness** [astronautlevel2/Anemone3DS#66]
Hello, 
Would it be possible to change the color of the labels for themes that are currently installed on the system? Or implement a feature that would let a user know if a theme is currently installed? 
Thank you for taking the time to read this, and for all your hard work.

**Comment by astronautlevel2** [comment]
There's a couple of ways to implement this - I'll figure out how to do it and probably include it in not the next update but the one after it.

**Comment by greenDarkness** [comment]
Thank you!

**Comment by LiquidFenrir** [comment]
Install indicator has been added with latest release, closing.
