### ISSUE TITLE
QR-CODE error

### ISSUE THREAD

**Issue by Ryumarubr** [astronautlevel2/Anemone3DS#67]
When I try to download a theme through 3dsthem, an error is displayed. File below.
https://drive.google.com/file/d/0B0EKfwYObAuKeC1CTGd3NXFFMUU/view?usp=drivesdk

The theme I tried to download, using the QR-CODE was this.
https://3dsthem.es/627

Note: Apparently, the scanner, is presenting errors in 3dsthem. Some themes are giving error in the scanning system.

**Comment by Helloman892** [comment]
Are you using the latest release, 1.1.1?
If you are, what model are you using? [N3DS, O3DS]

**Comment by astronautlevel2** [comment]
> Also, in said release, any theme that has a Unicode filename [that is, chars other than ASCII] crashes. The theme you linked is not one of those.

It doesn't actually crash, it just doesn't display properly until you restart the app.

**Comment by Helloman892** [comment]
The crash doesn't occur on my end.

**Comment by astronautlevel2** [comment]
What happens if you try without wifi?

**Comment by Helloman892** [comment]
No crash, but it hangs until it times out [I think].
