### ISSUE TITLE
Arm11 Dumps on start

### ISSUE THREAD

**Issue by Ailuros** [astronautlevel2/Anemone3DS#68]
I running the latest stable luma on the latest FW version (11.5) using the latest b9s (1.3) on a New 3DS XL and every time I try to launch Anemone I get about 10 seconds on the "Homebrew" splash screen then an arm11 dump saying press any key to shut down. I've tried deleting and reinstalling but it still happens.

**Comment by ZetaDesigns** [comment]
Try seleting a standard theme from the homemenu first

**Comment by Ailuros** [comment]
I'm using the CIA, btw.

**Comment by Ailuros** [comment]
Still happens. I went in and chose Black and it still dumped.

**Comment by ZetaDesigns** [comment]
How many themes do you have? It crashes if you have around 400+

**Comment by Ailuros** [comment]
About 15 pages worth in CTRXplorer, so about 300.

**Comment by astronautlevel2** [comment]
Out of curiosity, can you try renaming your Themes folder to something else, making a new one, and then putting like two or three themes into the new one?

**Comment by Ailuros** [comment]
That fixed it. I thought about 400+ was the number that made it crash. I wonder if there's anything else in my folders that could cause this issue?

**Comment by astronautlevel2** [comment]
There's a bug with the current release where anything more than 252 themes will cause a crash, new release soon:tm:

**Comment by Helloman892** [comment]
New release now™️
