### ISSUE TITLE
Crash on scanning non-theme QR code

### ISSUE THREAD

**Issue by Helloman892** [astronautlevel2/Anemone3DS#69]
As title states. When scanning a QR code that isn't a theme, Anemone 1.1.1 crashes. The QR code I found this with was, funnily enough, the download QR for the release [lol]. I could have a look at this myself, but I have no idea right now how to go about validating the download.

EDIT: Dump attached.
[crash_dump_00000026.zip](https://github.com/astronautlevel2/Anemone3DS/files/1287446/crash_dump_00000026.zip)

**Comment by TheSIlentLink** [comment]
I can confirm this and that it is still happening on version 1.2.1 Will try and get a crash dump later.

**Comment by Helloman892** [comment]
This was fixed in one of the latest commits to `stable` [it's my issue, I can't be bothered to find it].
