### ISSUE TITLE
Anemone3DS thinks that the splash is the theme and crash system when i try to install

### ISSUE THREAD

**Issue by jjckswitch** [astronautlevel2/Anemone3DS#70]
With QR-Code scanning from themeplaza.eu

**Comment by jjckswitch** [comment]
If try to scan QR Code in Splashes mode, the splash does not download

**Comment by Helloman892** [comment]
I couldn't replicate this, although some QR splashes took a while to download. What splash were you using? When you say 'crash system', what exactly happens? Could you provide the crash dump?

**Comment by Helloman892** [comment]
It's fine, I just found the error myself. I can scan a splash just fine into themes mode QR reader, but on attempting to install the theme, the console crashes.

**Comment by ZetaDesigns** [comment]
I could not reproduce this. Even when scanning a Theme in Splashmode, it doesnt crash. It just tries to add it to the Splash list, and then fails to install.

**Comment by jjckswitch** [comment]
Persona 5 - splash from themeplaza.eu, qr code.
Sorry for my English
In splash mode:
![top_0001](https://user-images.githubusercontent.com/30491079/30239740-54d2cf7c-957c-11e7-87de-22553ddc3786.png)
![bot_0001](https://user-images.githubusercontent.com/30491079/30239744-766a6f64-957c-11e7-813e-b5b69ab5bf46.png)
In theme mode when click "Install":
![image](https://user-images.githubusercontent.com/30491079/30239759-a07c63f2-957c-11e7-9d33-6e97321377e8.png)
![image](https://user-images.githubusercontent.com/30491079/30239769-bf507778-957c-11e7-82bd-f194549d4dc2.png)

**Comment by jjckswitch** [comment]
Anemone3DS can not sort splashes from a themes

**Comment by Helloman892** [comment]
You need to be in splash mode to install a theme.

@astronautlevel2 is working on this as we speak, 1.2.1 will patch it.

**Comment by jjckswitch** [comment]
In splash mode if i'm trying to download any splash - nothing happens, "NO SPLASHES FOUND"..

**Comment by jjckswitch** [comment]
i think this problem because splashes downloaded to the same folder as the themes, but i can't control it..

**Comment by Helloman892** [comment]
Again, this is a known issue. Currently you can't use the QR reader with no themes/splashes inside their respective directories.
