### ISSUE TITLE
Add FBI Theme Support

### ISSUE THREAD

**Issue by Ryumarubr** [astronautlevel2/Anemone3DS#73]
You could add support for installing FBI themes ?

**Comment by jupitteer** [comment]
FBI themes aren't very popular at all, and there aren't any themes sites that support them. I don't think this should be implemented.

**Comment by astronautlevel2** [comment]
Here's my view on FBI Themes:

Anemone3DS is supposed to be the be-all, end-all, one stop shop for custom themes on the 3DS. I'll probably implement FBI themes at some point if they take off - right now, they are **very** low priority.

**Comment by astronautlevel2** [comment]
Closing for now, will reopen if there's more interest in the future.
