### ISSUE TITLE
Fix Text Descriptions for Themes and Splashes

### ISSUE THREAD

**Issue by ricksee** [astronautlevel2/Anemone3DS#77]
Is it possible to fix some of the text for some themes and splashes. If the descriptions get long, it causes the text to overlap on one another, making the descriptions unreadable.

**Comment by Helloman892** [comment]
If it were me, I'd be asking "why are these descriptions so long" - but yes, this is known, and for now we're not 100% sure why it happens.

**Comment by Helloman892** [comment]
Missed this - v1.2.2 included a fix for this and a disclaimer as to why it isn't actually our fault.
