### ISSUE TITLE
Installing of splashes is broken.

### ISSUE THREAD

**Issue by DiamondMinerITA** [astronautlevel2/Anemone3DS#78]
When i try to install a splash it says "WARNING: Splashes are disabled in Luma Config"
I enabled them and tried with after and before payloads.
I think it's a bug

**Comment by DiamondMinerITA** [comment]
nvm, it was my console's fault.

**Comment by Ben-Fields** [comment]
> 
> 
> nvm, it was my console's fault.

Do you recall how you solved this issue on your console?

**Comment by Riteo** [comment]
> > nvm, it was my console's fault.
> 
> Do you recall how you solved this issue on your console?

No, sorry.
