### ISSUE TITLE
On boot, I hear BGM, but takes a few second for home screen to appear after that

### ISSUE THREAD

**Issue by thebeastgamer25** [astronautlevel2/Anemone3DS#79]
O3DS, 11.5.0

Latest Luma, latest anemone

**Comment by Helloman892** [comment]
* What theme are you using?
* Are you sure this is actually an Anemone issue?
* Does the same thing happen with the same theme in Themely?

**Comment by astronautlevel2** [comment]
Leaving this open to wait for OP to respond though I'm almost certain it's not an anemone issue.

**Comment by thebeastgamer25** [comment]
it's weird, after a bit of time, the issue was fixed. idk. if u want any more info, I'll give. I'm using the SimCity no logo theme from themeplaza. hey, alex, quick feature request: a themeplaza browser? Like themely? since all of th e drama with Erman, I can't trust him.


Sent from my Sprint Phone.
-------- Original message --------From: Alex Taber <notifications@github.com> Date: 9/15/17  9:46 PM  (GMT-05:00) To: astronautlevel2/Anemone3DS <Anemone3DS@noreply.github.com> Cc: Beast <rimorycz@icloud.com>, Author <author@noreply.github.com> Subject: Re: [astronautlevel2/Anemone3DS] On boot, I hear BGM,
  but takes a few second for home screen to appear after that (#79) 
Leaving this open to wait for OP to respond though I'm almost certain it's not an anemone issue.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/astronautlevel2/Anemone3DS","title":"astronautlevel2/Anemone3DS","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/astronautlevel2/Anemone3DS"}},"updates":{"snippets":[{"icon":"PERSON","message":"@astronautlevel2 in #79: Leaving this open to wait for OP to respond though I'm almost certain it's not an anemone issue."}],"action":{"name":"View Issue","url":"https://github.com/astronautlevel2/Anemone3DS/issues/79#issuecomment-329937083"}}}

**Comment by astronautlevel2** [comment]
I can't replicate it, probably some weird bug with the home menu or SD card.

Closing this for now - ThemePlaza.eu integration is definitely a planned feature :)

**Comment by thebeastgamer25** [comment]
:D awesome, thanks a lot man!!


Sent from my Sprint Phone.
-------- Original message --------From: Alex Taber <notifications@github.com> Date: 9/15/17  10:55 PM  (GMT-05:00) To: astronautlevel2/Anemone3DS <Anemone3DS@noreply.github.com> Cc: Beast <rimorycz@icloud.com>, Author <author@noreply.github.com> Subject: Re: [astronautlevel2/Anemone3DS] On boot, I hear BGM,
  but takes a few second for home screen to appear after that (#79) 
I can't replicate it, probably some weird bug with the home menu or SD card.
Closing this for now - ThemePlaza.eu integration is definitely a planned feature :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/astronautlevel2/Anemone3DS","title":"astronautlevel2/Anemone3DS","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/astronautlevel2/Anemone3DS"}},"updates":{"snippets":[{"icon":"PERSON","message":"@astronautlevel2 in #79: I can't replicate it, probably some weird bug with the home menu or SD card.\r\n\r\nClosing this for now - ThemePlaza.eu integration is definitely a planned feature :)"}],"action":{"name":"View Issue","url":"https://github.com/astronautlevel2/Anemone3DS/issues/79#issuecomment-329940531"}}}
