### ISSUE TITLE
Translation framework

### ISSUE THREAD

**Issue by astronautlevel2** [astronautlevel2/Anemone3DS#80]
Closing the following issues and moving everything to here:
#15 - Offer for Spanish translation
#43 - Offer for Romanian translation
#44 - German translation
#46 - French translation
#47 - Suggestion to use `gettext`

**Comment by Juanito9001** [comment]
ok, so you still need help with the spanish translation??

**Comment by ZetaDesigns** [comment]
Yes, looks like it @Juanito9001

**Comment by pilladoll** [comment]
I don't know if this it's the right place to post this. Sorry for inconvenience:
Spanish translation.

"Installing a single theme..." : "Instalar  tema..."
"Installing a shuffle theme..." : "Instalar tema aleatorio..."
"Installing BGM..." : "Instalar melodia..."
"NO THEMES FOUND" : "TEMAS NO ENCONTRADOS"
"Theme mode" : "Modo Tema"
"By: " : "por : "
"Install Shuffle Theme" : "Instalar tema aleatorio"
"Switch to Splashes" : "Cambiar a Splashes"
"Install Theme" : "Instalar tema"
"Queue Shuffle" : "Lista aleatoria"
"Install BGM" : "Instalar melodia"
"Preview Theme" : "Previsualizar tema"
"Scan QRCode" : "Escanear QRCode"
"Installing a splash..." : "Instalando splash..."
"Uninstalling a splash..." : "Desinstalando splash..."
"NO SPLASHES FOUND" : "SPLASHES NO ENCONTRADOS"
"Splash mode" : "Modo Splash"
"Install Splash" : "Instalando Splash"
"Switch to Themes" : "Cambiar a Temas"
"Delete current Splash" : "Borrar splash actual"
"Selected:" : "Seleccionados:"

**Comment by astronautlevel2** [comment]
Progress has been on the citro2d-translation branch, and translators will be notified once it's merged to master.

**Comment by astronautlevel2** [comment]
Finally implemented as-of a43cbcc
