### ISSUE TITLE
Crashing when SDCard is write-protected

### ISSUE THREAD

**Issue by Joelgp83** [astronautlevel2/Anemone3DS#81]
Hi guys, thanks for working on such a great 3DS app.  Got a lot of use out of it the pass few days since I installed it on mine and few other 3DSes.

On a particular friend of mine's 3DS (Red Old3DS xl; Sys 11.5, Luma 8.1.1, B9s v1.2, etc.), she has been using both 3DSthem.es and Themeplaza.eu sites to grab themes via Anemone3DS's QR feature.  She already has 33 themes installed, but when she goes to download another theme (any theme, it just so happens to be next one after the first 33 she's done), it scans the QR, begins downloading......and crashes with an exception screen.  Anybody encounter this?

And to answer the first obvious question, no, I don't have a crash dump on me at the moment, but I'll try to get one soon.

**Comment by astronautlevel2** [comment]
Hey there!

I can't seem to replicate this, so I can't do much w/o a crash dump, sorry.

Once you get one I'll be able to take a look though.

**Comment by ZetaDesigns** [comment]
Wild guess, but is her SDCard full maybe?

**Comment by Joelgp83** [comment]
*Total Facepalm Moment*

Figured it out -- Read-only switch on the SD card was on.  Anemone was attempting to download the data via QR, then during the write operation, got rejected by the card's read only switch -- Anemone apparantly doesn't handle this very well, and thus crashed.

We should retitle this "Anemone3DS not handling SD card Read only mode gracefully", perhaps, since that's the real problem.

**Comment by astronautlevel2** [comment]
Can someone test if this still happens after the rewrite?

**Comment by astronautlevel2** [comment]
Actually, the 3DS shouldn't load applications if the write protect switch is enabled, so this shouldn't be an actual issue.
