### ISSUE TITLE
Crash on boot

### ISSUE THREAD

**Issue by DietJoke** [astronautlevel2/Anemone3DS#82]
![img_20170917_113504_hdr](https://user-images.githubusercontent.com/32033355/30520008-7141928a-9b9c-11e7-9857-22589379de8e.jpg)

After installing a theme in Anemone the 3DS won't boot get this. Help!

**Comment by ZetaDesigns** [comment]
Clear Home Menu’s extdata by navigating to the following folder on your SD card: `/Nintendo 3DS/(32 Character ID)/(32 Character ID)/extdata/00000000/`

EUR Region: Delete `00000098`
JPN Region: Delete `00000082`
USA Region: Delete `0000008f`
CHN Region: Delete `000000A1`
KOR Region: Delete `000000A9`
TWN Region: Delete `000000B1`
