### ISSUE TITLE
App doesn't display full width characters properly

### ISSUE THREAD

**Issue by JohnnyScatman** [astronautlevel2/Anemone3DS#83]
When installing a theme with full width characters in the title or description, said characters do not display properly. The app just shows a single exclamation mark instead of the expected characters.

How to reproduce this error:
1. Install a theme with full width characters in the title and/or description ( For example: https://3dsthem.es/3345 )
2. Scroll down to the installed theme. The title shows up as just a single exclamation mark and the description is "Give your Nintendo 3DS some much needed !"

**Comment by astronautlevel2** [comment]
This is an issue with the system font not supporting fullwidth characters, which leaves us with more or less two options:

1. Not do anything about it as the system font makes other things a lot better (button glyphs, etc.)
2. Switch to a different font and use FreeType to generate glyphs.

Switching to FreeType has the unfortunate side effect of making the binary size larger (as we'd have to bundle a font and use our own glyphs for buttons) and potentially more memory intensive (which isn't an issue, I don't think we get anywhere close to full memory usage as is right now). I'm also not entirely familiar with freetype and already have a lot to work on for 1.3.0, so this is relatively low priority.

**Comment by SubstituteCS** [comment]
May I suggest side-loading a user supplied font? (and then bundling the font in a separate download). 
This would allow the user the chose between system font, bundled font, or their own choice of font.  
The check could just be a check if the file exists at PATH and to use it if it does.

**Comment by astronautlevel2** [comment]
We'd need to overhaul a lot of our current method of doing font, which isn't at the moment a very high priority.

**Comment by astronautlevel2** [comment]
Looked into this a bit, and there's no clean way of doing it.
