### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by 1mcuadros** [astronautlevel2/Anemone3DS#86]
Maybe some enhancements you can make:

-When you press y, make possible to go back with b.
-Maybe a text that says home menu - where? and in what context?
-Maybe put a music in the background.
-An option to change names of themes and splashes. - you can just rename the folder tho?
-Maybe trying to make a preview in top of the screed instead of the text or a way to change it by a button.
-A way to change the icon and bgm of them in the 3ds.
~~-Is it possible somehow to put sound to a splash?~~ thats nothing we have control over, its a luma thing
~~-Instead of "-" to Shuffle Theme you can write select.~~
-Scrollbar.
~~-Number of themes.~~

Sorry for my bad english, thanks.

EDIT: deleted all duplicates and left some notes - Zeta

**Comment by Helloman892** [comment]
* ~~something something give me a bit~~
* As Zeta added in his edit, we need to know what you mean by 'a text that says home menu'. Do you mean a text that states 'Start to quit'?
* Putting music in the background relies on two things - first of all, that the `.bcstm` handling is written, and secondly that the software be multithreaded (which, tl;dr, it isn't right now).
* Again as Zeta added in his edit, this would be completely pointless for two reasons:
  * Whenever anything updates the themes list (be it downloading from a QR code, deleting a theme, or even starting the app [!]), the name of each theme is determined based on its filename.
  * You can, as suggested, just rename any file or folder that isn't named to your liking.
* A smaller preview (à la Themely) would again require multithreading, which we aren't using quite yet.
* Please clarify 'changing the icon and bgm of them'.
* As Zeta says, sound is out of our domain. In fact, as far as I'm aware, a Luma splash shows before the speakers have even been initialised, so it wouldn't be possible anyway (correct me if I'm wrong).
* Writing 'Select' both looks awful and takes up a lot of space. The `-` button from the Wii is the closest symbol in the system font to the Select button.
* Scrollbar? What do you mean?
* Number of themes is extremely easy to implement, and as with your first suggestion, give me a bit and I'll add it in.

**Comment by astronautlevel2** [comment]
RE: 4, the name is actually not derived at all from the folder name but from the SMDH.

**Comment by ZetaDesigns** [comment]
RE: 9, he means some kind of (touch?) scroll bar displayed at the bottom screen probably

**Comment by Helloman892** [comment]
@ZetaDesigns That seems like a reasonable assumption, yes. Still waiting on OPs response, however.

**Comment by 1mcuadros** [comment]
-Yes, that's what I mean by using a scrollbar; you can already use the D-Pad and the Slide Pad to switch between themes, but there's no scrollbar to move faster along themes.
-Also there's also a problem that the text in the bottom and in the description in the top of the screens doesn't fit.
-You can put an option to sort the themes by date, size, name, etc.
-By saying a text that says home menu, I refer to say how to exit (the button start).
-And I don't know if you can put an option to edit in the 3ds the information of the archive SMDH so we can change the name of the theme we want.
-Preview BGM.
-Switching between previews without having to press y and then press y again to see another preview of other theme.
-By changing the icon and bgm of a theme I mean that you can change them by having the archives already in the 3ds and change them in the 3ds instead of the pc or maybe also switching or copying a bgm and an icon between themes (but I think these enhancements aren't that important and can be complex)

**Comment by Helloman892** [comment]
1. You can put that down to lazy development. Soon™.
1. Could you link us to a theme that exhibits that? I haven't seen any titles/descriptions that do what you're describing.
1. Sorting is less trivial than you'd think, but sorting by name is definitely coming over the next few weeks.
1. Quitting the app is not going to be bound to the start button in the next minor release - instead, it'll be on the new menu.
1. Editing binaries is not really my forte; @astronautlevel2 might know how to do this one.
1. Whilst previewing BGM is a fairly simple job, integrating it into the app is not so much. Previewing BGM would also rely on one of two things - the `.bcstm` handling to get written, something that (as far as I'm aware) none of the primary developers know an awful lot about; or the theme creator to be required to include an Ogg Vorbis file inside their theme archive.
1. This won't be necessary, as live previews are coming soon™.
1. You're right that this would be a complex thing to do. Altering the BGM is a preposterous idea (why on Earth would you edit perfectly good BGM ona 3DS, a system designed for games?) although altering the icon is very possible; however, it is far beyond the intended scope of Anemone and would be better suited to an image editor combined with an extracted (in a folder) theme.

**Comment by 1mcuadros** [comment]
For example in this large text themes
https://3dsthem.es/9369
https://3dsthem.es/13462
https://3dsthem.es/8723

**Comment by Helloman892** [comment]
The issue with the first and second themes is that they have too many characters for the standard. The maximum number of characters allowed by the standard (to my knowledge) is 64, and neither of those descriptions fit within that.

The third theme has a title that's too long - the maximum length for the title is 32 characters.

The issue here is the website you're using - [Theme Plaza](https://themeplaza.eu) disallows theme creators from going over the limits imposed by the SMDH standard. 3DSthem.es, on the other hand, is outdated and ultimately not recommended for use by anyone using Anemone.

The app plays far more nicely with properly formatted themes - the point is, this isn't our fault, it's the theme creator's.

**Comment by Helloman892** [comment]
Sorry for taking so long to respond.

The short answer is that those themes have too-long names, although in the UI overhaul coming After Whenever Astro Refactors:tm:, the font size will be reduced and it will be a non-issue.

The thing with the overflowing descriptions is something that we're still not sure on.

**Comment by Helloman892** [comment]
RE: What I said about the overflowing descriptions, fixed as of v1.2.2.
