### ISSUE TITLE
Download List

### ISSUE THREAD

**Issue by Ryumarubr** [astronautlevel2/Anemone3DS#87]
You could add a function, which allows you to scan the QR-CODES one after the other, creating a download listing, in the same style as Freeshop. To set up a download listing, which allows you to download the themes in order of listing, in the same way as Freeshop. If this function is added, you could also add a way to stop downloading, in order to return the download, even if the 3DS is turned off or restarted.

**Comment by astronautlevel2** [comment]
May consider this later.
