### ISSUE TITLE
Brazilian translation

### ISSUE THREAD

**Issue by Ryumarubr** [astronautlevel2/Anemone3DS#88]
"Installing a single theme..." : "Instalando  tema..."
"Installing a shuffle theme..." : "Instalando tema aleatorio..."
"Installing BGM..." : "Instalando BGM..."
"NO THEMES FOUND" : "NENHUM TEMA ENCONTRADO"
"Theme mode" : "Modo Tema"
"By: " : "Por : "
"Install Shuffle Theme" : "Instalar tema aleatório"
"Switch to Splashes" : "Mudar para Splashes"
"Install Theme" : "Instalar tema"
"Queue Shuffle" : "Listagem aleatória"
"Install BGM" : "Instalar BGM"
"Preview Theme" : "Pré-visualizar Tema"
"Scan QRCode" : "Escanear QR-CODE"
"Installing a splash..." : "Instalando Splash..."
"Uninstalling a splash..." : "Desinstalando Splash..."
"NO SPLASHES FOUND" : "NENHUM SPLASHES ENCONTRADO"
"Splash mode" : "Modo Splash"
"Install Splash" : "Instalar Splash"
"Switch to Themes" : "Mudar para Temas"
"Delete current Splash" : "Deletar Splash atual"
"Selected:" : "Selecionado:"

**Comment by ZetaDesigns** [comment]
Everything translation related belongs to #80
