### ISSUE TITLE
Slow with alot of themes (suggestion)

### ISSUE THREAD

**Issue by TheRealRitzer** [astronautlevel2/Anemone3DS#90]
Hi this isnt exactly an issue, but with themely it would load the app, and then load the themes slowly one by one so you wouldnt have to worry about it taking a long time to load into the menu. but with this homebrew, it takes forever to load to the menu if you have alot of themes. i had over 1k themes, and it felt like it just froze, and it seemed like the homebrew didnt work, but when i removed my themes, then it worked, so i suggest that you make it load themes one by one so it can enter the menu quicker.

**Comment by Helloman892** [comment]
Over 1k?

More importantly, this is simply because Anemone isn't multithreaded yet. Themely is.

Closing as this issue is already being worked on RE our [Trello](https://trello.com/b/F1YSa1VK).
