### ISSUE TITLE
More Enhancements?

### ISSUE THREAD

**Issue by 1mcuadros** [astronautlevel2/Anemone3DS#97]
Hello again, there are some improvements and options I think you can do to make Anemone better:

-I don't know if there is an option to preview the BGM of a theme, but if there isn't one please add it.
-A button to create another menu of options, for example, you can make that while you press the button "R", there shows you more options or maybe you could pass some of them so there can be more space/options, more text of the theme or maybe enlarging all.
-An option to loop the bgm of the theme always, in other words, to make the song of a theme to be repeated always. Including it, in the shuffle themes.
-Again, maybe adding the possibility to change the names of the themes, sorting them in other ways and to eliminate the themes we don't want (maybe a repeated theme).

**Comment by 1mcuadros** [comment]
Also is there any chance to eliminate the limit time a bgm can reproduce a song?, I think the limit is around. 1:25

**Comment by jupitteer** [comment]
@1mcuadros What you're referring to is just a hardcoded limit in the file size of BGMs. It's not necessarily a limit in the time, just the file size. If you want a bigger song, turn down the bitrate of the BGM when you're making it; the quality will go down, but you'll be able to fit a bigger song.

**Comment by astronautlevel2** [comment]
All enhancements listed here are now either duplicates, wontfixes, or implemented.
