### ISSUE TITLE
Stopped working for me

### ISSUE THREAD

**Issue by ANDYBellCo** [astronautlevel2/Anemone3DS#98]
Anemone 3ds worked just fine for a couple weeks and now for some reason every time I try to instal la new theme it instantly crashes and the "An exception occurred" screen pops up

I tried re installing it multiple times but nothing changed, I'm on sys 11.6.0 and I use Luma 3ds

**Comment by Helloman892** [comment]
Could you give us more details, i.e. a photograph of the crash screen? We can't help you without knowing which exception it is, exactly.

**Comment by ANDYBellCo** [comment]
right, sorry, I forgot to link those

https://image.ibb.co/e9YkJR/20171123_183904.jpg
https://image.ibb.co/cbgpdR/20171123_183859.jpg

**Comment by Helloman892** [comment]
Have you tried setting a default theme from the Home Menu? If you haven't, try that, and then try to open Anemone again.
Also, are you always trying the same theme? It may potentially be the theme itself.

**Comment by ANDYBellCo** [comment]
I've tried both, I've also tried to reinstall it via cia And fbi but nothing. The weird thing is it worked just fine until now.

**Comment by Helloman892** [comment]
Could you be more specific as to what 'both' means? Are you, or are you not, trying different themes? 

If you are always trying the same theme, could you upload a ZIP file containing the theme? My theory is that it's something to do with the theme itself, as I've run into a similar issue quite recently.

**Comment by ANDYBellCo** [comment]
I'm sorry for disappearing, I had a very busy couple of weeks.

What I was meant was, I've tried switcing to the default white theme and it still crashed when I installed a costum theme. I've also tried multiple themes so I know the problem is not the theme itself. This also happens with spalsh screens, I select one and it says it's installed then the moment I press start to exit it crashes and the splash theme doesn't show up. I have no idea why it stopped working, like I said it worked perfectly until a couple weeks ago

**Comment by Helloman892** [comment]
* Navigate to the following folder on your SD card: 
`/Nintendo 3DS/(32 Character ID)/(32 Character ID)/extdata/00000000/`
* Delete the corresponding folder for your region:
  * USA: `000002cd`
  * EUR: `000002ce`
  * JPN: `000002cc`

**Comment by RandomMan25XX** [comment]
I seem to be having the same issue, and even after deleting the 000002cd folder and using a theme that isn't the white one I still get a crash no matter which theme I try to install

**Comment by Garebear1903** [comment]
I follow your idea, but it still doesn't work!
