### ISSUE TITLE
themes dont install

### ISSUE THREAD

**Issue by majedcom** [astronautlevel2/Anemone3DS#99]
am on latest 3ds firmware on luma 3ds and I did installed anemone then I tried some custome themes and splash screen .. 1st time was ok then I changed theme and tried to install shuffle ones .. at that point after I install 1st one it will not show the other themes to be installed and when I reboot no themes at all are installed , also when I go inside theme home I find it on "don't use any theme" tab and even if I change or use shuffle with official or just the color theme it will revert to no theme as soon as I reboot .. any help is appreciated .
thx and regards

**Comment by Helloman892** [comment]
Hi there,

Sorry I didn't get to this sooner - Could you please attempt to clarify your issue? I'm not entirely sure what your situation is.

**Comment by majedcom** [comment]
ok .. 1st .. installation was ok with no problems then I installed a theme and a splash screen .. working like a charm .. then I decided I would like to try the shuffle themes and when I did so after selecting the theme it will allow me to install 1st one only .. when I go back to the 3ds after reboot I see its locked on no theme and even if I manually allow a theme it will revert to no theme. one thing I can add is I did try to install a bgm from another theme before trying the shuffle feature

**Comment by Helloman892** [comment]
Try:
* If you scan a QR code whilst having shuffle themes selected, the shuffle count won't reset and attempting to shuffle install will corrupt your theme extdata. To fix this bug, 
    1. Navigate to the following folder on your SD card: `/Nintendo 3DS/(32 Character ID)/(32 Character ID)/extdata/00000000/`
    2. Delete the corresponding folder for your region:
    * USA: `0000008f`
    * EUR: `00000098`
    * JPN: `00000082`
    * KOR: `000000A9`

(from [our wiki](https://github.com/astronautlevel2/Anemone3DS/wiki/Known-Bugs)).

**Comment by majedcom** [comment]
sorry for late reply , this did not solve the themes problems unfortunately , the issue is now when I install a theme its ok but if I turn the system off it revert to original white color and no theme and in theme settings I have use no theme locked

**Comment by Helloman892** [comment]
When you open Anemone, what version is shown in the bottom-left-hand corner?

**Comment by majedcom** [comment]
it shows v1.2.2 ,I got it from the official theme site everyone is using from discord, it takes long till it open fully maybe because I have many themes downloaded and rdy to use

**Comment by astronautlevel2** [comment]
Seems like a problem with your SD card rather than the installed theme.
